<?php
$phrases = array(
  'enGB' => array(
    'month01' => 'January',
    'month02' => 'February',
    'month03' => 'March',
    'month04' => 'April',
    'month05' => 'May',
    'month06' => 'June',
    'month07' => 'July',
    'month08' => 'August',
    'month09' => 'September',
    'month10' => 'October',
    'month11' => 'November',
    'month12' => 'December',
  ),
  'enUS' => array(
    'month01' => 'January',
    'month02' => 'February',
    'month03' => 'March',
    'month04' => 'April',
    'month05' => 'May',
    'month06' => 'June',
    'month07' => 'July',
    'month08' => 'August',
    'month09' => 'September',
    'month10' => 'October',
    'month11' => 'November',
    'month12' => 'December',
  ),
  'sp' => array(
    'month01' => 'enero',
    'month02' => 'febrero',
    'month03' => 'marzo',
    'month04' => 'abril',
    'month05' => 'mayo',
    'month06' => 'junio',
    'month07' => 'julio',
    'month08' => 'agosto',
    'month09' => 'septiembre',
    'month10' => 'octubre',
    'month11' => 'noviembre',
    'month12' => 'diciembre',
  ),
  'sp' => array(
    'month01' => 'janvier',
    'month02' => 'février',
    'month03' => 'mars',
    'month04' => 'avril',
    'month05' => 'mai',
    'month06' => 'juin',
    'month07' => 'juillet',
    'month08' => 'août',
    'month09' => 'septembre',
    'month10' => 'octobre',
    'month11' => 'novembre',
    'month12' => 'décembre',
  )
);
?>
