/*
 Joseph T. Parsons 2017
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");
var autoEntry=function(a,b){this.options=b;var c=this;a.append($("<form>").attr("class","input-group").append($("<span>").attr("class","input-group-btn").append($("<button>").attr({"class":"btn btn-success"}).text("Add")),$("<input>").attr({type:"text",name:this.options.name+"Bridge",id:this.options.name+"Bridge",class:"ui-autocomplete-input form-control",autocomplete:"off"}).autocompleteHelper(this.options.list)).submit(function(){var a=$("input[name="+c.options.name+"Bridge]",this);c.addEntry(a.attr("data-id"),
a.val());a.val("");return!1}));$('<input type="hidden" name="'+this.options.name+'" id="'+this.options.name+'">').insertAfter(a);$("<div>").attr("id",this.options.name+"List").insertAfter(a);"default"in b&&this.displayEntries(b.default);return this};
autoEntry.prototype={setOnAdd:function(a){this.options.onAdd=a},addEntry:function(a,b,c){var d=this;if(!a&&b)var e=$.when(this.options.resolveFromNames([b])).then(function(c){a=c[b].id});else!b&&a&&(e=$.when(this.options.resolveFromIds([a]).then(function(c){b=c[a].name})));$.when(e).then(function(){if(a)if($("span #"+d.options.name+"SubList"+a).length)dia.info("Duplicate entry."),$("#"+d.options.name+"Bridge").val("");else{var e=$("<span>");"allowedUsers"==d.options.name||"moderators"==d.options.name?
e=fim_buildUsernameTag(e,a,fim_getUsernameDeferred(a),!0):e.text(b);$("#"+d.options.name).val($("#"+d.options.name).val()+","+a);$("#"+d.options.name+"List").append($("<div>").attr({id:d.options.name+"SubList"+a,"class":"input-group input-group-sm m-1",style:"display: inline-block; width: auto; white-space: nowrap"}).append($("<span>").attr({"class":"input-group-btn",style:"display: inline-block; vertical-align: top"}).append($("<button>").attr({type:"button","class":"btn btn-danger"}).text("\u00d7").click(function(){d.removeEntry(a)})),
$("<span>").attr({"class":"input-group-addon",style:"display: inline-block"}).append(e)));if(!c&&d.options.onAdd)d.options.onAdd(a)}else dia.error("Invalid entry.")})},removeEntry:function(a){var b=this.options;$("#"+this.options.name).val($("#"+this.options.name).val().replace(new RegExp("(^|,)"+a+"(,|$)"),"$1$2").replace(/^,|(,),|,$/,"$1"));$("#"+this.options.name+"SubList"+a).fadeOut(500,function(){$(this).remove();if("function"===typeof b.onRemove)b.onRemove(a)})},displayEntries:function(a){var b=
"object"===typeof a?a:"string"===typeof a&&0<a.length?a.split(","):[];var c=this;$.when(this.options.resolveFromIds(b)).then(function(a){for(var d=0;d<b.length;d++)c.addEntry(b[d],a[b[d]].name,!0)})},getList:function(){return $("#"+this.options.name).val().split(",").filter(Number)}};var popup=function(){};
popup.prototype.login=function(){function a(a){$("#modal-login").modal("hide");a.userData.permissions.view?a.userData.permissions.post?dia.info("You are now logged in as "+a.userData.name+".","Logged In"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to post and have been silenced by an administrator. You may still view rooms which allow you access.","Logged In"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to view and have been banned by an administrator.","Logged In")}
function b(a){switch(a.string){case "sessionMismatchUserId":case "sessionMismatchBrowser":case "sessionMismatchIp":case "invalidSession":dia.error("The server rejected the stored session. Please login.");break;case "loginRequired":dia.error("A valid login must be provided. Please login.");break;case "invalid_grant":dia.error("The login provided is not valid. You most likely entered an incorrect password.");break;default:dia.error("Unknown error logging in: "+a.string)}}fim_renderHandlebarsInPlace($("#modals-login"));
$("#modal-login").modal();$("#loginForm").submit(function(){var c=$("#loginForm");standard.initialLogin({username:$("input[name=userName]",c).val(),password:$("input[name=password]",c).val(),finish:a,error:b});return!1});$("#modal-login").on("hide.bs.modal",function(){window.userId||standard.initialLogin({grantType:"anonymous",rememberMe:!1,finish:a,error:b})})};
popup.prototype.insertDoc=function(){$("#modal-insertDoc").modal();var a="",b=0,c=[],d="";"fileUploads"in serverSettings?(serverSettings.fileUploads.extensionChangesReverse={},jQuery.each(serverSettings.fileUploads.extensionChanges,function(a,b){b in serverSettings.fileUploads.extensionChangesReverse||(serverSettings.fileUploads.extensionChangesReverse[b]=[b]);serverSettings.fileUploads.extensionChangesReverse[b].push(b)}),jQuery.each(serverSettings.fileUploads.allowedExtensions,function(a,b){a=serverSettings.fileUploads.sizeLimits[b];
var c=serverSettings.fileUploads.fileContainers[b],d=serverSettings.fileUploads.extensionChangesReverse[b];$("table#fileUploadInfo tbody").append("<tr><td>"+(d?d.join(", "):b)+"</td><td>"+$l("fileContainers."+c)+"</td><td>"+$.formatFileSize(a,$l("byteUnits"))+"</td></tr>")}),"function"!==typeof FileReader?$("#uploadFileForm").html($l("uploadErrors.notSupported")):($("#uploadFileForm").submit(function(){filesList=$('input#fileUpload[type="file"]').prop("files");0==filesList.length?dia.error("Please select a file to upload."):
($("#fileUpload").fileupload(),$("#fileUpload").fileupload("add",{files:filesList,url:directory+"api/editFile.php?"+$.param({_action:"create",uploadMethod:"put",dataEncode:"binary",roomId:window.roomId,fileName:filesList.item(0).name,access_token:window.sessionHash,parentalAge:$("form#uploadFileForm select[name=parentalAge] option:selected").val(),parentalFlags:$("form#uploadFileForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get()}),type:"PUT",multipart:!1}),
$("#fileUpload").fileupload("destroy"),$("#modal-insertDoc").modal("hide"));return!1}),$("#fileUpload").bind("change",function(){var e=new FileReader,f=new FileReader;console.log("FileReader triggered.");$("#imageUploadSubmitButton").attr("disabled","disabled").button({disabled:!0});0===this.files.length?dia.error("No files selected!"):1<this.files.length?dia.error("Too many files selected!"):(console.log("FileReader started."),a=this.files[0].name,b=this.files[0].size,c=a.split("."),d=c[c.length-
1],d in serverSettings.fileUploads.extensionChanges&&(d=serverSettings.fileUploads.extensionChanges[d]),-1===$.inArray(d,$.toArray(serverSettings.fileUploads.allowedExtensions))?$("#uploadFileFormPreview").html($l("uploadErrors.badExtPersonal")):b>serverSettings.fileUploads.sizeLimits[d]?$("#uploadFileFormPreview").html($l("uploadErrors.tooLargePersonal",{fileSize:serverSettings.fileUploads.sizeLimits[d]})):($("#uploadFileFormPreview").html("Loading Preview..."),e.readAsBinaryString(this.files[0]),
e.onloadend=function(){window.btoa(e.result)},f.readAsDataURL(this.files[0]),f.onloadend=function(){$("#uploadFileFormPreview").html(fim_messagePreview(serverSettings.fileUploads.fileContainers[d],this.result))},$("#imageUploadSubmitButton").removeAttr("disabled").button({disabled:!1})))}))):$("#insertDocUpload").html("Disabled.");return!1};
popup.prototype.viewStats=function(){$("#modal-stats").modal();$("table#viewStats > tbody").html("");for(i=1;10>=i;i+=1)$("table#viewStats > tbody").append("<tr><th>"+i+"</th></tr>");fimApi.getStats({roomId:window.roomId},{each:function(a){$("table#viewStats > thead > tr").append($("<th>").append($("<span>").attr({"class":"roomName","data-roomId":a.id}).text(a.name)));var b=0;jQuery.each(a.users,function(a,d){$("table#viewStats > tbody > tr").eq(b).append($("<td>").append(fim_buildUsernameTag($("<span>"),
d.id,fim_getUsernameDeferred(d.id),!0),$("<span>").text("("+d.messageCount+")")));b++})},end:function(){windowDraw()}})};
popup.prototype.settings={init:function(){var a={disableFormatting:16,disableImage:32,disableVideos:64,reversePostOrder:1024,showAvatars:2048,audioDing:8192,disableFx:262144,disableRightClick:1048576,usTime:16777216,twelveHourTime:33554432,webkitNotifications:536870912};fimApi.getUsers({info:["self","profile"],id:userId},{each:function(a){console.log(a);var b=[];b={r:0,g:0,b:0};var d=[];d={r:0,g:0,b:0};new autoEntry($("#changeSettingsForm [name=ignoreListContainer]"),{name:"ignoreList","default":a.ignoredUsers,
list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});new autoEntry($("#changeSettingsForm [name=friendsListContainer]"),{name:"friendsList","default":a.friendedUsers,list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});new autoEntry($("#changeSettingsForm [name=watchRoomsContainer]"),{name:"watchRooms","default":a.watchRooms,list:"rooms",resolveFromIds:Resolver.resolveRoomsFromIds,resolveFromNames:Resolver.resolveRoomsFromNames});
$("#fontPreview").attr("style",a.messageFormatting);defaultFormatting=a.messageFormatting.split(";");defaultFormattingObj={};jQuery.each(defaultFormatting,function(a,b){pair=b.split(":");defaultFormattingObj[pair[0]]=pair[1]});a.profile&&$("#profile").val(a.profile);"font-weight"in defaultFormattingObj&&"bold"==defaultFormattingObj["font-weight"]&&($("#fontPreview").css("font-weight","bold"),$("#defaultBold").attr("checked","checked"));$("#defaultBold").change(function(){$("#defaultBold").is(":checked")?
$("#fontPreview").css("font-weight","bold"):$("#fontPreview").css("font-weight","normal")});"font-style"in defaultFormattingObj&&"italic"==defaultFormattingObj["font-style"]&&$("#defaultItalics").attr("checked","checked");$("#defaultItalics").change(function(){$("#defaultItalics").is(":checked")?$("#fontPreview").css("font-style","italic"):$("#fontPreview").css("font-style","normal")});window.serverSettings.formatting.fonts?(jQuery.each(window.serverSettings.formatting.fonts,function(a,b){$("#defaultFace").append($("<option>").attr({value:a,
style:"font-family: "+b}).attr(defaultFormattingObj["font-family"]==b?{selected:"selected"}:{}).text(a))}),$("#defaultFace").change(function(){$("#fontPreview").css("fontFamily",$("#defaultFace > option:selected").attr("data-font"))})):$("#defaultFace").hide();window.serverSettings.formatting.color?("color"in defaultFormattingObj&&($("#defaultColour").css("background-color",defaultFormattingObj.color),d=defaultFormattingObj.color.slice(4,-1).split(","),d={r:d[0],g:d[1],b:d[2]}),$("#defaultColour").ColorPicker({color:d,
onShow:function(a){$(a).fadeIn(500)},onHide:function(a){$(a).fadeOut(500)},onChange:function(a,b,c){defaultColour=c.r+","+c.g+","+c.b;$("#defaultColour").css("background-color","rgb("+defaultColour+")");$("#fontPreview").css("color","rgb("+defaultColour+")")}})):$("#defaultColour").hide();window.serverSettings.formatting.highlight?("background-color"in defaultFormattingObj&&($("#defaultHighlight").css("background-color",defaultFormattingObj["background-color"]),b=defaultFormattingObj["background-color"].slice(4,
-1).split(","),b={r:b[0],g:b[1],b:b[2]}),$("#defaultHighlight").ColorPicker({color:b,onShow:function(a){$(a).fadeIn(500)},onHide:function(a){$(a).fadeOut(500)},onChange:function(a,b,c){defaultHighlight=c.r+","+c.g+","+c.b;$("#defaultHighlight").css("background-color","rgb("+defaultHighlight+")");$("#fontPreview").css("background-color","rgb("+defaultHighlight+")")}})):$("#defaultHighlight").hide();fimApi.getRooms({roomIds:[a.defaultRoomId]},{each:function(a){$("#defaultRoom").val(a.name).attr("data-id",
a.id)}});jQuery.each(a.parentalFlags,function(a,b){$("input[name=parentalFlags][value="+b+"]").attr("checked",!0)});$('input[name=privacyLevel][value="'+a.privacyLevel+'"]').prop("checked",!0)}});"vanilla"!==window.serverSettings.branding.forumType&&$("#settings5profile").hide(0);$("#defaultRoom").autocompleteHelper("rooms");window.webproDisplay.theme&&$('#theme > option[value="'+window.webproDisplay.theme+'"]').attr("selected","selected");$("#theme").change(function(){$("#stylesjQ").attr("href",
"client/css/"+this.value+"/jquery-ui-1.8.16.custom.css");$("#stylesVIM").attr("href","client/css/"+this.value+"/fim.css");$.cookie("webpro_theme",this.value,{expires:14});window.webproDisplay.theme=this.value;return!1});window.webproDisplay.fontSize&&$('#fontsize > option[value="'+window.webproDisplay.fontSize+'"]').attr("selected","selected");$("#fontsize").change(function(){$("body").css("font-size",this.value+"em");$.cookie("webpro_fontsize",this.value,{expires:14});window.webproDisplay.fontSize=
this.value;windowResize();return!1});snd.volume&&$("#audioVolume").attr("value",100*snd.volume);$("#audioVolume").change(function(){$.cookie("webpro_audioVolume",this.value,{expires:14});snd.volume=this.value/100;return!1});settings.showAvatars&&$("#showAvatars").attr("checked","checked");settings.reversePostOrder&&$("#reversePostOrder").attr("checked","checked");settings.disableFormatting&&$("#disableFormatting").attr("checked","checked");settings.disableVideo&&$("#disableVideo").attr("checked",
"checked");settings.disableImage&&$("#disableImage").attr("checked","checked");$("#showAvatars, #reversePostOrder, #disableFormatting, #disableVideo, #disableImage").change(function(){var b=$(this).attr("id");$(this).is(":checked")&&!settings[b]?(settings[b]=!0,$("#messageList").html(""),$.cookie("webpro_settings",Number($.cookie("webpro_settings"))+a[b],{expires:14})):!$(this).is(":checked")&&settings[b]&&(settings[b]=!1,$("#messageList").html(""),$.cookie("webpro_settings",Number($.cookie("webpro_settings"))-
a[b],{expires:14}));standard.changeRoom(window.roomId)});settings.audioDing&&$("#audioDing").attr("checked","checked");settings.disableFx&&$("#disableFx").attr("checked","checked");settings.disableRightClick&&$("#disableRightClick").attr("checked","checked");settings.webkitNotifications&&$("#webkitNotifications").attr("checked","checked");$("#audioDing, #disableFx, #webkitNotifications, #disableRightClick").change(function(){var b=$(this).attr("id");$(this).is(":checked")&&!settings[b]?(settings[b]=
!0,$.cookie("webpro_settings",Number($.cookie("webpro_settings"))+a[b],{expires:14}),"disableFx"===b&&(jQuery.fx.off=!0),"webkitNotifications"===b&&(notify.webkitNotifySupported()?notify.webkitNotifyRequest():dia.error("Notifications are not supported on your browser."))):!$(this).is(":checked")&&settings[b]&&(settings[b]=!1,$.cookie("webpro_settings",Number($.cookie("webpro_settings"))-a[b],{expires:14}),"disableFx"===b&&(jQuery.fx.off=!1))});$("#changeSettingsForm").submit(function(){var a=[];$("#defaultBold").is(":checked")&&
a.push("bold");$("#defaultItalics").is(":checked")&&a.push("italic");fimApi.editUserOptions("edit",{defaultFontface:$("#defaultFace option:selected").val(),defaultFormatting:a,defaultHighlight:"rgba(0, 0, 0, 0)"===$("#fontPreview").css("background-color")?null:$("#fontPreview").css("background-color").slice(4,-1),defaultColor:$("#fontPreview").css("color").slice(4,-1),defaultRoomId:$("#defaultRoom").attr("data-id"),watchRooms:$("#watchRooms").val().split(","),ignoreList:$("#ignoreList").val().split(","),
friendsList:$("#friendsList").val().split(","),profile:$("#profile").val(),parentalAge:$("form#changeSettingsForm select[name=parentalAge] option:selected").val(),parentalFlags:$("form#changeSettingsForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),privacyLevel:$("input[name=privacyLevel]:radio:checked").val()},{each:function(a){console.log(a)},end:function(){dia.info("Your settings have been updated successfully.");$("#changeSettingsDialogue").empty().remove();
$(".colorpicker").empty().remove()},error:function(a){errorsList=[];for(var b=0;b<a.responseJSON.editUserOptions.length;b++)errorsList.push("<li>"+b+": "+a.responseJSON.editUserOptions[b].exception.details+"</li>");dia.error("Some of your settings have been updated. However, the following values were unable to be processed:<ul>"+errorsList.join()+"</ul>")}});window.history.back();return!1});return!1}};
popup.prototype.uploads={init:function(){fimApi.getFiles({userIds:[window.userId]},{each:function(a){for(var b=[],c=0;c<a.parentalFlags.length;c++)a.parentalFlags[c]&&b.push($l("parentalFlags."+a.parentalFlags[c]));$("#viewUploadsBody").append($("<tr>").append($('<td align="center">').append($('<img style="max-width: 200px; max-height: 200px;" />').attr("src",directory+"file.php?"+$.param({sha256hash:a.sha256hash,thumbnailWidth:200,thumbnailHeight:200}))).append("<br />").append($("<span>").text(a.fileName))).append($('<td align="center">').text(a.fileSizeFormatted)).append($('<td align="center">').text($l("parentalAges."+
a.parentalAge)).append("<br />").append(b.join(", "))).append($('<td align="center">').append($("<button>").attr("class","btn btn-primary").click(function(){fimApi.editUserOptions("edit",{avatar:serverSettings.installUrl+"file.php?sha256hash="+a.sha256hash+"&thumbnailWidth=200&thumbnailHeight=200"},{end:function(a){"avatar"in a?dia.error(a.avatar.string):dia.info("Your avatar has been updated. It will not appear in your old messages.")}})}).text($l("uploads.setToAvatar")).prepend($('<i class="fa fa-picture-o" aria-hidden="true"></i> ')))))},
end:function(){$("#viewUploadsBody img").load(windowDraw)}})}};
popup.prototype.editRoom={options:{roomId:0},setOptions:function(a){for(i in a)this.options[i]=a[i]},init:function(a){var b=this;this.setOptions(a);var c=0!=this.options.roomId?"edit":"create";$("#editRoomForm input[name=allowPosting]").change(function(){$(this).is(":checked")?$(this).closest("fieldset").attr("disabled","disabled"):$(this).closest("fieldset").removeAttr("disabled","disabled")});moderatorsList=new autoEntry($("#moderatorsContainer"),{name:"moderators",list:"users",onAdd:function(a){"edit"===
c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post","moderate","properties","grant"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post"])},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});allowedUsersList=new autoEntry($("#allowedUsersContainer"),{name:"allowedUsers",list:"users",onAdd:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,
a,[""])},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});allowedGroupsList=new autoEntry($("#allowedGroupsContainer"),{name:"allowedGroups",list:"groups",onAdd:function(a){"edit"===c&&fimApi.editRoomPermissionGroup(b.options.roomId,a,["post"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionGroup(b.options.roomId,a,[""])},resolveFromIds:Resolver.resolveGroupsFromIds,resolveFromNames:Resolver.resolveGroupsFromNames});fimApi.getCensorLists({roomId:0!=
this.options.roomId?this.options.roomId:null,includeWords:0},{each:function(a){if(a.status)var b=a.status;else if("white"===a.listType)b="block";else if("black"===a.listType)b="unblock";else throw"Bad logic.";$("#editRoomForm [name=censorLists]").append($("<label>").attr("class","btn btn-secondary m-1").text(a.listName).prepend($("<input>").attr({type:"checkbox",name:"censorLists",value:a.listId}).attr(a.listOptions&2?{disabled:"disabled"}:{}).attr("block"==b?{checked:"checked"}:{})))}});0!=this.options.roomId&&
fimApi.getRooms({id:this.options.roomId},{each:function(a){var b=[],c=[];jQuery.each(a.userPermissions,function(a,d){d.moderate&&d.properties&&d.grant?c.push(a):d.post&&b.push(a)});allowedUsersList.displayEntries(b);moderatorsList.displayEntries(c);var d=[];jQuery.each(a.groupPermissions,function(a,b){b.post&&d.push(a)});allowedGroupsList.displayEntries(d);"view"in a.defaultPermissions&&$("#editRoomForm input[name=allowViewing]").prop("checked",!0);"post"in a.defaultPermissions&&$("#editRoomForm input[name=allowPosting]").prop("checked",
!0);$("#editRoomForm input[name=name]").val(a.name);$("#editRoomForm input[name=official]").prop("checked",a.official);$("#editRoomForm input[name=hidden]").prop("checked",a.hidden);jQuery.each(a.parentalFlags,function(a,b){$("#editRoomForm input[name=parentalFlags][value="+b+"]").prop("checked",!0)});$("#editRoomForm select[name=parentalAge] option[value="+a.parentalAge+"]").attr("selected","selected")}});$("#editRoomForm").submit(function(){var a={},e={};"create"===c&&(allowedUsersList.getList().forEach(function(b){a["+"+
b]=["view","post"]}),moderatorsList.getList().forEach(function(b){a["+"+b]=["view","post","moderate"]}),allowedGroupsList.getList().forEach(function(a){e["+"+a]=["post"]}));defaultPermissions=[];$("#editRoomForm input[name=allowViewing]").is(":checked")&&defaultPermissions.push("view");$("#editRoomForm input[name=allowPosting]").is(":checked")&&defaultPermissions.push("post");fimApi.editRoom(b.options.roomId,c,{name:$("#editRoomForm input[name=name]").val(),defaultPermissions:defaultPermissions,userPermissions:a,
groupPermissions:e,parentalAge:$("#editRoomForm select[name=parentalAge] option:selected").val(),parentalFlags:$("#editRoomForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),censorLists:$("#editRoomForm input[name=censorLists]:checked").map(function(){return $(this).attr("value")}).get(),official:$("#editRoomForm input[name=official]").is(":checked"),hidden:$("#editRoomForm input[name=hidden]").is(":checked")},{end:function(a){window.location.hash="#";dia.full({content:$l("editRoom.finish."+
c+"Title")+'<br /><br /><form action="#room='+a.id+'"><div class="input-group"><input autofocus type="text" value="'+currentLocation+"#room="+a.id+'" name="url" class="form-control"  /><span class="input-group-btn"><button class="btn btn-primary">Go!</button></span></div></form>',title:$l("editRoom.finish."+c+"Message"),buttons:{Open:function(){window.location.hash="#room="+a.id},Okay:function(){}}})}});return!1});return!1}};
popup.prototype.online=function(){$("#modal-online").modal();fimApi.getActiveUsers({},{refresh:6E4,begin:function(){$("#onlineUsers").html("")},each:function(a){var b=[];jQuery.each(a.rooms,function(a,d){b.length&&b.push($("<span>").text(", "));b.push(fim_buildRoomNameTag($("<span>"),d.id,fim_getRoomNameDeferred(d.id)))});$("#onlineUsers").append($("<tr>").append($("<td>").append(fim_buildUsernameTag($("<span>"),a.id,fim_getUsernameDeferred(a.id),!0))).append($("<td>").append(b)))}});$("#modal-online").on("hidden.bs.modal",
function(){fimApi.getActiveUsers({},{close:!0})})};
popup.prototype.kicks={dateOptions:{year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"numeric",second:"numeric"},init:function(){fimApi.getKicks(params,{each:function(a){jQuery.each(a.kicks,function(b,c){console.log(c);$("#kickedUsers").append($("<tr>").append($("<td>").append($('<span class="userName userNameTable">').attr({"data-userId":a.userId,style:a.userNameFormat}).text(a.userName))).append($("<td>").append($('<span class="userName userNameTable">').attr({"data-userId":c.kickerId,style:c.kickerNameFormat}).text(c.kickerName))).append($("<td>").append($('<span class="roomName roomNameTable">').attr({"data-roomId":c.roomId}).text(c.roomName))).append($("<td>").text(fim_dateFormat(c.set,
dateOptions))).append($("<td>").text(fim_dateFormat(c.expires,dateOptions))).append($("<td>").append($("<button>").click(function(){standard.unkick(a.userId,c.roomId)}).text("Unkick"))))})}})}};
popup.prototype.kick=function(){$("#modal-kick").modal();$("#userName").autocompleteHelper("users");$("#roomNameKick").autocompleteHelper("rooms");$("#kickUserForm").submit(function(){var a=$("#kickUserForm > #userName").val(),b=$("#kickUserForm > #userName").attr("data-id"),c=$("#kickUserForm > #roomNameKick").val(),d=$("#kickUserForm > #roomNameKick").attr("data-id"),e=Math.floor(Number($("#kickUserForm > #time").val()*Number($("#kickUserForm > #interval > option:selected").attr("value")))),f=!0,
g=!0;c&&!d&&(f=$.when(Resolver.resolveUsersFromNames([a]).then(function(c){b=c[a].id})));c&&!d&&(g=$.when(Resolver.resolveRoomsFromNames([c]).then(function(a){d=a[c].id})));$.when(f,g).then(function(){standard.kick(b,d,e)});return!1});return!1};
popup.prototype.archive={options:{searchText:"",resultLimit:40,searchUser:0,firstMessage:null,page:0,roomId:0},messageData:{},init:function(a){var b=this;for(i in a)this.options[i]=a[i];this.options.roomId||(this.options.roomId=window.roomId);$("#active-view-archive form#archiveSearch input[name=searchText]").unbind("change").bind("change",function(){b.update("searchText",$(this).val());b.retrieve()});$("#active-view-archive form#archiveSearch input[name=searchUser]").unbind("change").bind("change",
function(){console.log("search user",$(this).attr("data-id"));b.update("searchUser",$(this).attr("data-id"));b.retrieve()}).autocompleteHelper("users");$("#active-view-archive button[name=archiveNext]").unbind("click").bind("click",function(){b.nextPage()});$("#active-view-archive button[name=archivePrev]").unbind("click").bind("click",function(){b.prevPage()});$("#active-view-archive button[name=export]").unbind("click").bind("click",function(){popup.exportArchive()});b.retrieve()},setRoom:function(a){this.options.roomId!=
a&&(this.options.roomId=a,this.retrieve())},setFirstMessage:function(a){this.options.firstMessage=a;this.options.lastMessage=null;this.retrieve()},setLastMessage:function(a){this.options.lastMessage=a;this.options.firstMessage=null;this.retrieve()},nextPage:function(){fim_atomicRemoveHashParameterSetHashParameter("firstMessage","lastMessage",$("#active-view-archive table.messageTable tr:last-child > td > span.messageText").attr("data-messageid"))},prevPage:function(){fim_atomicRemoveHashParameterSetHashParameter("lastMessage",
"firstMessage",$("#active-view-archive table.messageTable tr:first-child > td > span.messageText").attr("data-messageid"))},retrieve:function(){var a=this;fimApi.getMessages({roomId:a.options.roomId,userIds:[a.options.searchUser],messageTextSearch:a.options.searchText,messageIdStart:a.options.firstMessage,messageIdEnd:a.options.lastMessage,archive:1,page:a.options.page},{reverseEach:a.options.firstMessage?!0:!1,end:function(b){$("#active-view-archive table.messageTable > tbody").html("");$("#active-view-archive button[name=archivePrev]").prop("disabled",
!1);this.messageData={};jQuery.each(b,function(b,d){$("#active-view-archive table.messageTable > tbody").append(fim_messageFormat(d,"table").append($("<td>").append($('<a href="#archive#room='+a.options.roomId+"#lastMessage="+d.id+'">Show</a>'))));a.messageData[d.id]=d});2>b.length?(a.options.firstMessage&&$("#active-view-archive button[name=archivePrev]").prop("disabled",!0),a.options.lastMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",!0)):(a.options.firstMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",
!1),a.options.lastMessage&&$("#active-view-archive button[name=archivePage]").prop("disabled",!1))}})},update:function(a,b){this.options[a]=b}};
popup.prototype.exportArchive=function(){dia.full({id:"exportDia",content:'<form method="post" action="#" onsubmit="return false;" id="exportDiaForm">How would you like to export the data?<br /><br /><table align="center"><tr><td>Format</td><td><select id="exportFormat"><option value="bbcodetable">BBCode Table</option><option value="csv">CSV List (Excel, etc.)</option></select></td></tr><tr><td colspan="2" align="center"><button type="submit">Export</button></td></tr></table></form>',width:600});
$("#exportDiaForm").submit(function(){switch($("#exportFormat option:selected").val()){case "bbcodetable":var a="";$("#archiveMessageList").find("tr").each(function(){var b=$(this).find("td:eq(0) .userNameTable").text(),c=$(this).find("td:eq(1)").text(),d=$(this).find("td:eq(2)").text();for(i in[0,2]){switch(i){case 0:var e=b;break;case 2:e=d}var f=$(this).find("td:eq("+i+") > span"),g=f.css("color"),h=f.css("backgroundColor"),k=f.css("fontFamily"),l="bold"==f.css("fontWeight")?!0:!1,m="underline"==
f.css("textDecoration")?!0:!1;f="line-through"==f.css("textDecoration")?!0:!1;if(g||h||k)b='[span="'+(g?"color: "+g+";":"")+(h?"background-color: "+h+";":"")+(k?"font: "+k+";":"")+'"]'+b+"[/span]";l&&(b="[b]"+b+"[/b]");m&&(b="[u]"+b+"[/u]");f&&(b="[s]"+b+"[/s]");switch(i){case 1:b=e;break;case 3:d=e}}a+=b+"|"+c+"|"+d+"\n"});a='<textarea style="width: 100%; height: 1000px;">[table=head]User|Time|Message\n'+a+"[/table]</textarea>";break;case "csv":a="",$("#archiveMessageList").find("tr").each(function(){var b=
$(this).find("td:nth-child(1) .userNameTable").text(),c=$(this).find("td:nth-child(2)").text(),d=$(this).find("td:nth-child(3)").text();a+="'"+b+"', '"+c+"', '"+d+"'\n"}),a='<textarea style="width: 100%; height: 600px;">'+a+"</textarea>"}dia.full({id:"exportTable",content:a,width:"1000"});return!1})};var standard=function(){};standard.prototype.initialLogin=function(a){oldFinish=a.finish;a.finish=function(b){oldFinish&&oldFinish(b);window.anonId||($.cookie("webpro_username",a.username,{expires:14}),$.cookie("webpro_password",a.password,{expires:14}),fimApi.getUnreadMessages(null,{each:function(a){fim_showMissedMessage(a)}}));window.roomId||(window.roomId=b.userData.defaultRoomId?b.userData.defaultRoomId:1);fim_renderHandlebarsInPlace($("#entry-template"));fim_hashParse()};standard.login(a)};
standard.prototype.login=function(a){a.start&&a.start();fimApi.login({grant_type:a.grantType,username:a.username,password:a.password,access_token:a.sessionHash,refresh_token:a.refreshToken,client_id:"WebPro"},{end:function(b){"userData"in b?(window.activeLogin=b,window.userId=b.userData.id,window.anonId=b.userData.anonId,window.permissions=b.userData.permissions):window.activeLogin||(dia.error("The login did not return proper information. The page will reload in 3 seconds..."),setTimeout(function(){location.reload()},
3E3));window.sessionHash=b.access_token;a.finish&&a.finish(b);b.expires&&b.refresh_token&&($.cookie("webpro_refreshToken",b.refresh_token),setTimeout(function(){standard.login({grantType:"refresh_token",refreshToken:b.refresh_token})},1E3*b.expires/2));fimApi.getRooms({roomIds:window.serverSettings.officialRooms.concat(window.activeLogin.userData.favRooms).concat(window.activeLogin.userData.watchRooms)},{begin:function(){$("#navbar div[name=favRoomsList]").html("");$("#navbar div[name=watchRoomsList]").html("")},
each:function(a){var b=$("<a>").attr({href:"#room="+a.id,"class":"dropdown-item"}).text(a.name);-1!=window.activeLogin.userData.favRooms.indexOf(a.id)&&$("#navbar div[name=favRoomsList]").append(b.clone());-1!=window.activeLogin.userData.watchRooms.indexOf(a.id)&&$("#navbar div[name=watchRoomsList]").append(b.clone());a.official&&$("#navbar div[name=officialRoomsList]").append(b.clone())}});"function"===typeof prepopup&&(prepopup(),prepopup=!1);return!1},error:function(b){a.error&&a.error(b);return!1}})};
standard.prototype.logout=function(){$.cookie("webpro_username",null);$.cookie("webpro_password",null);$.cookie("webpro_refreshToken",null);fimApi.getMessages(null,{close:!0});fimApi.getActiveUsers(null,{close:!0});fimApi.getUnreadMessages(null,{close:!0});$("#logout").parent().show();$("#login").parent().hide();popup.login()};
standard.prototype.deleteRoom=function(a){$.post(directory+"api/editRoom.php","action=delete&messageId="+messageId+"&access_token="+sessionHash,function(a){switch(a.editRoom.errStr){case "":console.log("Message "+messageId+" deleted.");break;case "nopermission":dia.error("You do not have permission to administer this room.");break;case "badroom":dia.error("The specified room does not exist.")}return!1})};
standard.prototype.kick=function(a,b,c){fimApi.kickUser(a,b,c,{end:function(){dia.info("The user has been kicked.","Success");$("#kickUserDialogue").dialog("close")}});return!1};
standard.prototype.unkick=function(a,b){fimApi.unkickUser(a,b,{exception:function(a){switch(a.string){case "nopermission":dia.error("You do not have permision to moderate this room.");break;case "baduser":case "badroom":dia.error("Odd error: the user or room sent do not seem to exist.");break;default:fimApi.getDefaultExceptionHandler()(a)}},end:function(){dia.info("The user has been unkicked.","Success");$("#kickUserDialogue").dialog("close")}});return!1};
standard.prototype.deleteMessage=function(a,b){fimApi.deleteMessage(a,b,{end:function(){dia.info("The message was deleted.")}});return!1};function fim_eURL(a){if("encodeURIComponent"in window)return window.encodeURIComponent(a).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A").replace(/%20/g,"+");if("escape"in window)return window.escape(a).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A").replace(/%20/g,"+");throw Error("You dun goofed.");}function fim_eXMLAttr(a){return a.replace(/\"/g,"&quot;").replace(/\\/g,"\\\\")}
function fim_toBottom(){document.getElementById("messageListContainer").scrollTop=document.getElementById("messageListContainer").scrollHeight}function fim_faviconFlash(){"images/favicon.ico"===$("#favicon").attr("href")?$("#favicon").attr("href","images/favicon2.ico"):$("#favicon").attr("href","images/favicon.ico")}function fim_messagePopup(a){"undefined"!=typeof notify&&"object"===typeof window.webkitNotifications&&notify.webkitNotify("images/favicon.ico","New Message",a)}
function fim_dateFormat(a,b){var c=new Date;c.setTime(1E3*a);if("undefined"===typeof b){b={hour:"numeric",minute:"numeric",second:"numeric"};var d=new Date;d=(new Date(d.getFullYear(),d.getMonth(),d.getDate(),0,0,0,0)).getTime()/1E3;a<d&&(b.day="numeric",b.month="numeric",b.year="2-digit")}return c.toLocaleString(void 0,b)}
function fim_youtubeParse(a){if(a.match(regexs.youtubeFull)||a.match(regexs.youtubeShort)){var b="";null!==a.match(regexs.youtubeFull)?b=a.replace(regexs.youtubeFull,"$8"):null!==a.match(regexs.youtubeShort)&&(b=a.replace(regexs.youtubeShort,"$5"));return settings.disableVideo?$("<a>").attr({href:"https://www.youtu.be/"+b,target:"_BLANK"}).text("[Youtube Video]"):$("<iframe>").attr({width:560,height:315,src:"https://www.youtube.com/embed/"+b+"?rel=0",frameborder:0,allowfullscreen:!0})}return fim_formatAsUrl(a)}
function fim_formatAsImage(a){return $('<a target="_BLANK" class="imglink">').attr("href",a).append(settings.disableImage?$("<span>").text("[IMAGE]"):$('<img style="max-width: 250px; max-height: 250px;" />').attr("src",a))}function fim_formatAsVideo(a){return settings.disableVideo?$('<a target="_BLANK">[Video]</a>').attr("href",a):$("<video controls>").attr("src",a)}
function fim_formatAsAudio(a){return settings.disableVideo?$('<a target="_BLANK">[Audio]</a>').attr("href",a):$("<audio controls>").attr("src",a)}function fim_formatAsEmail(a){return $('<a target="_BLANK">').attr("href","mailto:".email).text(a)}function fim_formatAsUrl(a){return a.match(/^(http|https|ftp|data|gopher|sftp|ssh)\:/)?$('<a target="_BLANK">').attr("href",a).text(a):$("<span>").text("[Broken Link: "+a+"]")}
function fim_showMissedMessage(a){a.roomId==window.roomId||$("#missedMessage"+a.roomId+"_"+a.messageId).length||($(".missedMessage").find('[data-roomId="'+a.roomId+'"]').find(".jGrowl-close").click(),$.jGrowl($("<span>").attr({"class":"missedMessage",id:"missedMessage"+a.roomId+"_"+a.messageId,"data-roomId":a.roomId}).text("New message from ").append($("<strong>").attr("style",a.senderNameFormat).text(a.senderName)).append(" has been made in ").append($('<a style="font-weight: bold">').attr("href",
"#room="+a.roomId).text(a.roomName).click(function(){$(this).parent().parent().parent().parent().find(".jGrowl-close").click()})).append(a.missedMessages?$("<span>").text("(Total unread messages: "+a.missedMessages+")"):""),{sticky:!0,close:function(){fimApi.markMessageRead(a.roomId)}}))}
function fim_messageFormat(a,b){var c=a.text,d=a.time,e=a.id,f=a.roomId,g=a.flag,h=Number(a.userId);a=fim_getUsernameDeferred(h);c=c.replace(/\</g,"&lt;").replace(/\>/g,"&gt;").replace(/\n/g,"<br />");c=c.replace(/(file\.php\?sha256hash\=[a-f0-9]{64})/,function(a){return a+"&"+$.param(fimApi.mergeDefaults({},{parentalAge:window.activeLogin.userData.parentalAge?window.activeLogin.userData.parentalAge:null,parentalFlags:window.activeLogin.userData.parentalFlags?window.activeLogin.userData.parentalFlags:
null}))});switch(g){case "source":c=fim_youtubeParse(c);break;case "image":c=fim_formatAsImage(c);break;case "video":c=fim_formatAsVideo(c);break;case "audio":c=fim_formatAsAudio(c);break;case "email":c=fim_formatAsEmail(c);break;case "url":case "text":case "html":case "archive":case "other":c=fim_formatAsUrl(c);break;default:c=$("<span>").text(c),c.html(c.text().replace(regexs.url,function(a){if(a.match(regexs.url2)){var b=a.replace(regexs.url2,"$2");a=a.replace(regexs.url2,"$1")}else b="";return a.match(regexs.youtubeFull)||
a.match(regexs.youtubeShort)?fim_youtubeParse(a).prop("outerHTML")+b:a.match(regexs.image)?fim_formatAsImage(a).prop("outerHTML")+b:fim_formatAsUrl(a).prop("outerHTML")+b})),/^\/me/.test(c.text())?(c.text(c.text().replace(/^\/me/,"")),$.when(a).then(function(a){c.html($('<span style="color: red; padding: 10px; font-weight: bold;">').text("* "+a[h].name+" "+c).prop("outerHTML"))})):/^\/topic/.test(c.text())&&(c.text(c.text().replace(/^\/topic/,"")),$("#topic").text(c),$.when(a).then(function(a){c.html($('<span style="color: red; padding: 10px; font-weight: bold;">').text("* "+
a[h].name+' changed the topic to "'+c+'".').prop("outerHTML"))})),jQuery.each(serverSettings.emoticons,function(a,b){c.contents().filter(function(){return 3===this.nodeType}).each(function(){$(this).replaceWith($(this).text().replace(new RegExp(b.emoticonText.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"),"gi"),function(){return $("<img>").attr("src",b.emoticonFile).prop("outerHTML")}))})})}switch(b){case "table":var k=$('<tr style="word-wrap: break-word;">').attr({id:"archiveMessage' + messageId + '"}).append($("<td>").append(fim_buildUsernameTag($('<span class="userName userNameTable">'),
h,a,!0))).append($("<td>").text(fim_dateFormat(d))).append($("<td>").append(fim_buildMessageLine(c,e,h,f,d,a).append(c)));break;case "list":b=fim_buildMessageLine(c,e,h,f,d,a),settings.showAvatars&&b.popover({content:function(){return fim_dateFormat($(this).attr("data-time"))},html:!1,trigger:"hover",placement:"bottom"}),k=$("<span>").attr({id:"message"+e,"class":"messageLine"+(settings.showAvatars?" messageLineAvatar":"")}).append($('<span class="usernameDate">').append(fim_buildUsernameTag($("<span>"),
h,a)).append(settings.showAvatars?"":$('<span class="date">').css({"padding-right":"10px","letter-spacing":"-1px"}).text("@ ").append($("<em>").text(fim_dateFormat(d))))).append(b)}return k}
function fim_buildUsernameTag(a,b,c,d){$.when(c).then(function(c){var e=c[b].name,g=c[b].nameFormat,h=c[b].avatar?c[b].avatar:"client/images/blankperson.png";a.attr({"class":"userName"+(settings.showAvatars||d?" userNameAvatar":""),style:settings.showAvatars?"":g,"data-userId":b,"data-userName":e,"data-avatar":h,tabindex:1E3}).append(settings.showAvatars||d?$("<img>").attr({alt:e,src:h?h:"client/images/blankperson.png"}):"").append(!settings.showAvatars||d?$("<span>").text(e):"");a.popover({content:function(){var a=
$('<div class="row no-gutters">'),d=$('<div class="col">').append($('<div class="userName">').attr({"data-userId":b,style:g}).css("font-weight","bold").text(e),$("<hr>"));c[b].bio&&d.append($("<div>").text(c[b].bio));c[b].profile&&d.append($("<div>").append($("<em><strong>Profile</strong></em>"),": ",$("<a>").attr("href",c[b].profile).text(c[b].profile)));c[b].joinDate&&d.append($("<div>").append($("<em><strong>Member Since</strong></em>"),": ",$("<span>").text(fim_dateFormat(c[b].joinDate,{year:"numeric",
month:"numeric",day:"numeric"}))));a.append($('<div class="col-sm-auto">').append($('<img style="max-height: 200px; max-width: 200px;" class="mr-2">').attr("src",h)),d);return a.prop("outerHTML")},html:!0,trigger:"hover"}).on("show.bs.popover",function(a){console.log($(this).data("bs.popover"),$(this).data("bs.popover").tip);$($(this).data("bs.popover").tip).css({"max-width":"600px"})})});return a}
function fim_buildRoomNameTag(a,b,c){$.when(c).then(function(c){console.log("pairs: ",b,c);c=c[b].name;a.attr({"class":"roomName","data-roomId":b,"data-roomName":c,tabindex:1E3}).append($("<a>").attr("href","#room="+b).text(c))});return a}
function fim_buildMessageLine(a,b,c,d,e,f){var g=$("<span>");g.attr({"class":"messageText","data-messageId":b,"data-roomId":d,"data-time":e,tabindex:1E3}).append(a);if(window.userId==c&&window.permissions.editOwnPosts)g.on("dblclick",function(){var a=$("<textarea>").text($(this).text()).onEnter(function(){fimApi.editMessage(d,b,{message:a.val()});$(this).replaceWith(fim_buildMessageLine(a.val(),b,c,d,e,f))});$.each(this.attributes,function(){a.attr(this.name,this.value)});$(this).replaceWith(a)});
$.when(f).then(function(a){g.attr("style",a[c].messageFormatting)});return g}function fim_getUsernameDeferred(a){return $.when(Resolver.resolveUsersFromIds([a]))}function fim_getRoomNameDeferred(a){return $.when(Resolver.resolveRoomsFromIds([a]))}
function fim_messagePreview(a,b){switch(a){case "image":return'<img src="'+b+'" style="max-height: 200px; max-width: 200px;" />';case "video":return'<video src="'+b+'" style="max-height: 200px; max-width: 200px;">Video Preview Not Supported</video>';case "audio":return'<audio src="'+b+'" style="max-height: 200px; max-width: 200px;">Audio Preview Not Supported</video>';case "text":return"No Preview Available";case "html":return"No Preview Available";case "archive":return"No Preview Available";case "other":return"No Preview Available";
default:return"No Preview Available"}}
function fim_newMessage(a,b,c){if(!(-1<$.inArray(b,messageIndex))){if(0<$("#message"+b).length)$("#message"+b).replaceWith(c);else{var d=!1;$("#messageList .messageLine").each(function(){if(settings.reversePostOrder){if($(".messageText",this).attr("data-messageId")<b)return $(c).insertBefore(this),d=!0,!1}else if($(".messageText",this).attr("data-messageId")>b)return $(c).insertBefore(this),d=!0,!1});d||(settings.reversePostOrder?$("#messageList").prepend(c):$("#messageList").append(c))}messageIndex[a].push(b);
100<=messageIndex[a].length&&($("#message"+messageIndex[a][0]).remove(),messageIndex[a]=messageIndex[a].slice(1,99));settings.reversePostOrder||fim_toBottom();if(window.isBlurred){settings.audioDing&&snd.play();window.clearInterval(timers.t3);timers.t3=window.setInterval(fim_faviconFlash,1E3);if("object"===typeof window.external&&"undefined"!==typeof window.external.msIsSiteMode&&"undefined"!==typeof window.external.msSiteModeActivate)try{window.external.msIsSiteMode()&&window.external.msSiteModeActivate()}catch(e){}notify.webkitNotifySupported()&&
settings.webkitNotifications&&notify.webkitNotify("images/favicon.ico","New Message",$(c).text())}$(".messageLine .messageText, .messageLine .userName, body").unbind("keydown");$(".messageLine .messageText").bind("keydown",function(a){if("contextMenu"===window.restrictFocus)return!0;if(38===a.which)return $(this).parent().prev(".messageLine").children(".messageText").focus(),!1;if(37===a.which||39===a.which)return $(this).parent().children(".userName").focus(),!1;if(40===a.which)return $(this).parent().next(".messageLine").children(".messageText").focus(),
!1});$(".messageLine .userName").bind("keydown",function(a){if("contextMenu"===window.restrictFocus)return!0;if(38===a.which)return $(this).parent().prev(".messageLine").children(".userName").focus(),!1;if(39===a.which||37===a.which)return $(this).parent().children(".messageText").focus(),!1;if(40===a.which)return $(this).parent().next(".messageLine").children(".userName").focus(),!1})}}
var settings={disableFormatting:window.webproDisplay.settingsBitfield&16?!0:!1,disableImage:window.webproDisplay.settingsBitfield&32?!0:!1,disableVideos:window.webproDisplay.settingsBitfield&64?!0:!1,reversePostOrder:window.webproDisplay.settingsBitfield&1024?!0:!1,showAvatars:window.webproDisplay.settingsBitfield&2048?!0:!1,audioDing:window.webproDisplay.settingsBitfield&8192?!0:!1,disableFx:window.webproDisplay.settingsBitfield&262144?!0:!1,disableRightClick:window.webproDisplay.settingsBitfield&
1048576?!0:!1,usTime:window.webproDisplay.settingsBitfield&16777216?!0:!1,twelveHourTime:window.webproDisplay.settingsBitfield&33554432?!0:!1,webkitNotifications:window.webproDisplay.settingsBitfield&536870912?!0:!1},regexs={url:/((http|https|ftp|data|gopher|sftp|ssh):(\/\/|)(((([a-zA-Z0-9]+)\.)+(aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|xxx|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cs|cu|cv|cx|cy|cz|dd|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf]pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|rs|ru|\u0440\u0444|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|ss|st|su|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|za|zm|zw))|localhost)(:([0-9]+)|)((\/)([^\ \n\<\>\"]*)|))/g,
url2:/^(.+)([\"\?\!\.])$/,image:/^(.+)\.(jpg|jpeg|gif|png|svg|svgz|bmp|ico)$/,youtubeFull:/^((http|https):(\/\/|)(www\.|)youtube\.com\/([^\ ]*?)(\?|\&)(w|v)=([a-zA-Z0-9-_]+))$/i,youtubeShort:/^((http|https):(\/\/|)(www\.|)youtu\.be\/([a-zA-Z0-9-_]+))$/i},userNameToId={},userIdToData={};
function windowResize(){var a=$(window).width(),b=$(window).height();$("#messageListContainer").css("height",Math.floor(b-($("#messageListCard").height()-$("#messageListContainer").height())-$("#textentryBoxMessage").height()-$("#navbar").height()-50));$("#menu").hasClass("ui-accordion")&&$("#menu").accordion("refresh");$(".ui-widget-overlay").each(function(){$(this).height(b);$(this).width(a)});$(".ui-dialog-content").each(function(){$(this).dialog("option","width")>a&&$(this).dialog("option","width",
a);($(this).dialog("option","height")>b||$(this).height()>b)&&$(this).dialog("option","height",b);$(this).dialog("option","position",{my:"center",at:"center",of:window})})}function windowBlur(){window.isBlurred=!0}function windowFocus(){window.isBlurred=!1;window.clearInterval(timers.t3);$("#favicon").attr("href",favicon)}function windowDraw(){console.log("Redrawing window.");windowResize();return!1}
function windowDynaLinks(){window.userId?($("#navbar a[name=logout]").show(),$("#navbar a[name=login]").hide()):($("#navbar a[name=logout]").hide(),$("#navbar a[name=login]").show())}
function fim_showLoader(){$('<div class="ui-widget-overlay" id="waitOverlay"></div>').appendTo("body").width($(document).width()).height($(document).height());$('<img src="images/ajax-loader.gif" id="waitThrobber" />').appendTo("body").css("position","absolute").offset({left:($(window).width()-220)/2,top:($(window).height()-19)/2})}function fim_hideLoader(){$("#waitOverlay, #waitThrobber").empty().remove()};var fimApi=function(){this.requestDefaults={close:!1,timerId:1,refresh:-1,timeout:5E3,cache:!1,begin:function(){},error:function(){},exception:function(){},each:function(){},reverseEach:!1,end:function(){},async:!0,action:null,autoId:!1};this.timers={};this.done=function(a,b){return function(c){var d=c[b?b:Object.keys(c)[0]];a.begin(d);a.reverseEach&&(d=d.reverse());$.each(d,function(b,c){a.each(c)});a.end(d,c.metadata)}};this.fail=function(a,b){return function(c){"responseJSON"in c||(c.responseJSON=
JSON.parse(c.responseText));if("exception"in c.responseJSON)if("The access token provided has expired"==c.responseJSON.exception.details)$.cookie("webpro_username")?standard.login({username:$.cookie("webpro_username"),password:$.cookie("webpro_username"),finish:b}):(standard.logout(),dia.error("Your login has expired. Please login again."));else return a.exception(c.responseJSON.exception);else return a.error(c)}};this.timer=function(a,b,c){a.close?(console.log("close "+b+"_"+a.timerId,fimApi.timers),
clearInterval(fimApi.timers[b+"_"+a.timerId]),delete fimApi.timers[b+"_"+a.timerId]):(c(a),-1<a.refresh&&(clearInterval(fimApi.timers[b+"_"+a.timerId]),fimApi.timers[b+"_"+a.timerId]=setInterval(function(){c(a)},a.refresh)))};this.registerDefaultExceptionHandler=function(a){this.requestDefaults.exception=a};this.getDefaultExceptionHandler=function(){return this.requestDefaults.exception}};
fimApi.prototype.login=function(a,b){a=fimApi.mergeDefaults(a,{grant_type:"password",username:null,password:null,access_token:null,refresh_token:null,client_id:""});b=fimApi.mergeDefaults(b,fimApi.requestDefaults);return $.ajax({url:directory+"validate.php",type:"POST",data:a,timeout:b.timeout,cache:b.cache}).done(function(a){b.end(a.login)}).fail(function(a){b.error(a.responseJSON.exception)})};
fimApi.prototype.getUsers=function(a,b){a=fimApi.mergeDefaults(a,{info:["self","groups","profile"],access_token:window.sessionHash,id:null,userIds:null,userNames:null,userNameSearch:null});b=fimApi.mergeDefaults(b,fimApi.requestDefaults);(function(){$.ajax({type:"get",url:directory+"api/user.php",data:a,timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getUsers(a,b)}))})()};
fimApi.prototype.createUser=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);return $.ajax({type:"post",url:directory+"api/user.php",data:fimApi.mergeDefaults(a,{name:null,password:null,birthDate:null,email:null}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getUsers(a,b)}))};
fimApi.prototype.getRooms=function(a,b){a=fimApi.mergeDefaults(a,{access_token:window.sessionHash,id:null,roomIds:null,roomNames:null,roomNameSearch:null,permFilter:null,page:null});b=fimApi.mergeDefaults(b,fimApi.requestDefaults);(function(){$.ajax({type:"get",url:directory+"api/room.php",data:a,timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getRooms(a,b)}))})()};
fimApi.prototype.getEventsFallback=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);fimApi.timer(b,"getEventsFallback",function(b){$.ajax({type:"get",url:directory+"stream.php",data:fimApi.mergeDefaults(a,{fallback:!0,access_token:window.sessionHash,streamType:null,queryId:null,lastEvent:null,lastMessage:null}),timeout:b.timeout,cache:b.cache}).done(function(a){fimApi.done(b)(a)}).fail(function(c){b.refresh&&fimApi.getEventsFallback(null,{close:!0});fimApi.fail(b,function(){fimApi.getEventsFallback(a,
b)})(c)})})};
fimApi.prototype.getMessages=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);fimApi.timer(b,"getMessages",function(b){$.ajax({type:"get",url:directory+"api/message.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash,roomId:null,userIds:null,messageIdEnd:null,messageIdStart:null,page:null,messageTextSearch:null,archive:b.autoId?window.requestSettings[a.roomId].firstRequest:!1}),timeout:b.timeout,cache:b.cache}).done(function(a){fimApi.done(b)(a)}).fail(function(c){b.refresh&&fimApi.getMessages(null,
{close:!0});fimApi.fail(b,function(){fimApi.getMessages(a,b)})(c)})})};fimApi.prototype.sendMessage=function(a,b,c){b=fimApi.mergeDefaults(b,{access_token:window.sessionHash,ignoreBlock:!1,message:null,flag:null});c=fimApi.mergeDefaults(c,fimApi.requestDefaults);$.ajax({url:directory+"api/message.php?"+$.param({roomId:a}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(fimApi.done(c)).fail(fimApi.fail(c,function(){fimApi.sendMessage(a,b,c)}))};
fimApi.prototype.editMessage=function(a,b,c,d){c=fimApi.mergeDefaults(c,{ignoreBlock:!1,message:null,flag:null});d=fimApi.mergeDefaults(d,fimApi.requestDefaults);$.ajax({url:directory+"api/message.php?"+$.param({_action:"edit",access_token:window.sessionHash,id:b,roomId:a}),type:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(fimApi.done(d)).fail(fimApi.fail(d,function(){fimApi.editMessage(a,b,c,d)}))};
fimApi.prototype.deleteMessage=function(a,b,c){c=fimApi.mergeDefaults(c,fimApi.requestDefaults);$.ajax({url:directory+"api/message.php?"+$.param({_action:"delete",access_token:window.sessionHash,id:b,roomId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(fimApi.done(c)).fail(fimApi.fail(c,function(){fimApi.deleteMessage(a,b,c)}))};
fimApi.prototype.getUnreadMessages=function(a,b){b=fimApi.mergeDefaults(b,fimApi.mergeDefaults({timeout:3E4,refresh:3E4},fimApi.requestDefaults));fimApi.timer(b,"getUnreadMessages",function(b){$.ajax({type:"get",url:directory+"api/unreadMessages.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(function(c){b.refresh&&fimApi.getUnreadMessages(null,{close:!0});fimApi.fail(b,function(){fimApi.getUnreadMessages(a,b)})(c)})})};
fimApi.prototype.getFiles=function(a,b){a=fimApi.mergeDefaults(a,{access_token:window.sessionHash,userIds:"",fileIds:""});b=fimApi.mergeDefaults(b,fimApi.requestDefaults);b.close&&clearInterval(fimApi.timers["getFiles_"+b.timerId]);(function(){$.ajax({type:"get",url:directory+"api/files.php",data:a,timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getFiles(a.requestSettings)}))})()};
fimApi.prototype.getStats=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);$.ajax({type:"get",url:directory+"api/stats.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash,roomId:null,number:10}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b,"roomStats")).fail(fimApi.fail(b,function(){fimApi.getStats(a,b)}))};
fimApi.prototype.getKicks=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);(function(){$.ajax({type:"get",url:directory+"api/kick.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash,roomId:null,userId:null}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getKicks(a,b)}))})()};
fimApi.prototype.getCensorLists=function(a,b){a=fimApi.mergeDefaults(a,{access_token:window.sessionHash,roomId:null,listIds:null,includeWords:1});b=fimApi.mergeDefaults(b,fimApi.requestDefaults);(function(){$.ajax({type:"get",url:directory+"api/getCensorLists.php",data:a,timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getCensorLists(a,b)}))})()};
fimApi.prototype.getActiveUsers=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);fimApi.timer(b,"getActiveUsers",function(b){$.ajax({type:"get",url:directory+"api/userStatus.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash,roomIds:null,userIds:null,onlineThreshold:null}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b,"users")).fail(function(c){b.refresh&&fimApi.getActiveUsers(null,{close:!0});fimApi.fail(b,function(){fimApi.getActiveUsers(a,b)})(c)})})};
fimApi.prototype.getGroups=function(a,b){b=fimApi.mergeDefaults(b,fimApi.requestDefaults);$.ajax({type:"get",url:directory+"api/group.php",data:fimApi.mergeDefaults(a,{access_token:window.sessionHash,groupIds:null,groupNames:null,groupNameSearch:null}),timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.getGroups(a,b)}))};
fimApi.prototype.acHelper=function(a){return function(b,c){$.ajax({type:"get",url:directory+"api/acHelper.php",data:{access_token:window.sessionHash,list:a,search:b.term},success:function(a){c($.map(a.entries,function(a,b){return{label:a,value:b}}))}})}};
fimApi.prototype.kickUser=function(a,b,c,d){d=fimApi.mergeDefaults(d,fimApi.requestDefaults);$.ajax({url:directory+"api/kick.php?"+$.param({access_token:window.sessionHash,roomId:b,userId:a}),type:"POST",data:{length:c},timeout:d.timeout,cache:d.cache}).done(fimApi.done(d)).fail(fimApi.fail(d,function(){fimApi.kickUser(a,b,c,d)}))};
fimApi.prototype.unkickUser=function(a,b,c){c=fimApi.mergeDefaults(c,fimApi.requestDefaults);$.ajax({url:directory+"api/kick.php?"+$.param({access_token:window.sessionHash,_action:"delete",roomId:b,userId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(fimApi.done(c)).fail(fimApi.fail(c,function(){fimApi.unkickUser(a,b,c)}))};
fimApi.prototype.markMessageRead=function(a,b){var c={access_token:window.sessionHash,roomId:a};b=fimApi.mergeDefaults(b,fimApi.requestDefaults);$.ajax({url:directory+"api/markMessageRead.php",type:"POST",data:c,timeout:b.timeout,cache:b.cache}).done(fimApi.done(b)).fail(fimApi.fail(b,function(){fimApi.markMessageRead(a,b)}))};
fimApi.prototype.editUserOptions=function(a,b,c){b=fimApi.mergeDefaults(b,{defaultFormatting:null,defaultColor:null,defaultHighlight:null,defaultRoomId:null,watchRooms:null,favRooms:null,ignoreList:null,friendsList:null,profile:null,defaultFontface:null,parentalAge:null,parentalFlags:null,avatar:null,privacyLevel:null});c=fimApi.mergeDefaults(c,fimApi.requestDefaults);$.ajax({url:directory+"api/userOptions.php?"+$.param({access_token:window.sessionHash,_action:a?a:"edit"}),type:"POST",data:b,timeout:c.timeout,
cache:c.cache}).done(fimApi.done(c)).fail(fimApi.fail(c,function(){fimApi.editUserOptions(a,b,c)}))};fimApi.prototype.favRoom=function(a){this.editUserOptions("create",{favRooms:[a]})};fimApi.prototype.unfavRoom=function(a){this.editUserOptions("delete",{favRooms:[a]})};fimApi.prototype.watchRoom=function(a){this.editUserOptions("create",{watchRooms:[a]})};fimApi.prototype.unwatchRoom=function(a){this.editUserOptions("delete",{watchRooms:[a]})};
fimApi.prototype.editRoom=function(a,b,c,d){c=fimApi.mergeDefaults(c,{access_token:window.sessionHash,name:null,defaultPermissions:null,userPermissions:null,groupPermissions:null,censorLists:null,parentalAge:null,parentalFlags:null,hidden:null,official:null});d=fimApi.mergeDefaults(d,fimApi.requestDefaults);$.ajax({url:directory+"api/room.php?"+$.param({id:a,_action:b}),method:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(fimApi.done(d)).fail(fimApi.fail(d,function(){fimApi.editRoom(a,c,d)}))};
fimApi.prototype.createRoom=function(a,b){fimApi.editRoom(null,"create",a,b)};fimApi.prototype.deleteRoom=function(a,b){fimApi.editRoom(a,"delete",{},b)};fimApi.prototype.undeleteRoom=function(a,b){fimApi.editRoom(a,"undelete",{},b)};fimApi.prototype.editRoomPermissionUser=function(a,b,c){var d={};d["*"+b]=c;fimApi.editRoom(a,"edit",{userPermissions:d})};fimApi.prototype.editRoomPermissionGroup=function(a,b,c){var d={};d["*"+b]=c;fimApi.editRoom(a,"edit",{groupPermissions:d})};
fimApi.prototype.editUserStatus=function(a,b,c){b=fimApi.mergeDefaults(b,{status:null,typing:null});c=fimApi.mergeDefaults(c,fimApi.requestDefaults);$.ajax({url:directory+"api/userStatus.php?"+$.param({_action:"edit",access_token:window.sessionHash,roomIds:[a]}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(fimApi.done(c)).fail(fimApi.fail(c,function(){fimApi.editUserStatus(a,b,c)}))};fimApi.prototype.ping=function(a,b){this.editUserStatus(a,{},b)};
fimApi.prototype.changeAvatar=function(a,b){this.editUserOptions({avatarHash:a},b)};fimApi.prototype.mergeDefaults=function(a,b){var c={},d;for(d in a){if(!(d in b))throw"Invalid data in object call: "+d;null!==a[d]&&void 0!==a[d]&&(c[d]=a[d])}for(d in b)d in c||null===b[d]||(c[d]=b[d]);return c};fimApi.prototype.jsonify=function(a,b){a=void 0===a?{}:Object.create(a);for(var c in b)b[c]in a&&(a[b[c]]=JSON.stringify(a[b[c]]));return a};var Resolver=function(){function a(){}a.cacheEntry=function(b,c){-1===a["cached"+b+"Ids"].indexOf(c.id)&&(a["cached"+b+"Ids"].push(Number(c.id)),a["cached"+b+"Names"].push(String(c.name)),a["cached"+b+"Properties"].push(c))};a.resolve=function(b,c,d){var e=$.Deferred(),f={},g=[],h=[],k=c.charAt(0).toUpperCase()+c.slice(1)+"s",l=b+k;if("id"==c)for(k=0;k<d.length;k++)d[k]=Number(d[k]);k=function(c){if(-1!==a["cached"+l].indexOf(c))f[c]=a["cached"+b+"Properties"][a["cached"+l].indexOf(c)];else if(-1!==
a["waiting"+l].indexOf(c)){var d=setInterval(function(){console.log(["resolveWaitRetry",l,c,a["cached"+l]]);-1!==a["cached"+l].indexOf(c)&&(clearInterval(d),console.log(["resolveFoundInCacheAfterWait",l,c,f[c]]),f[c]=a["cached"+b+"Properties"][a["cached"+l].indexOf(c)],h.splice($.inArray(c,h),1))},100);h.push(c)}else a["waiting"+l].push(c),g.push(c)};for(var m=0;m<d.length;m++)k(d[m]);0<g.length&&(d={},d[l]=g,fimApi["get"+b.charAt(0).toUpperCase()+b.slice(1)+"s"](d,{each:function(d){a.cacheEntry(b,
d);f[d[c]]=d},end:function(){g=[]}}));if(0<h.length||0<g.length)var n=setInterval(function(){console.log("unresolvedItemsWait");0==h.length&&0==g.length&&(console.log("unresolvedItemsComplete"),clearInterval(n),e.resolve(f))},100);else e.resolve(f);return e.promise()};a.resolveUsersFromIds=function(b){return a.resolve("user","id",b)};a.resolveUsersFromNames=function(b){return a.resolve("user","name",b)};a.resolveRoomsFromIds=function(b){return a.resolve("room","id",b)};a.resolveRoomsFromNames=function(b){return a.resolve("room",
"name",b)};a.resolveGroupsFromIds=function(b){return a.resolve("group","id",b)};a.resolveGroupsFromNames=function(b){return a.resolve("group","name",b)};a.cacheduserIds=[];a.cacheduserNames=[];a.cacheduserProperties=[];a.waitinguserIds=[];a.waitinguserNames=[];a.waitinguserProperties=[];a.cachedroomIds=[];a.cachedroomNames=[];a.cachedroomProperties=[];a.waitingroomIds=[];a.waitingroomNames=[];a.waitingroomProperties=[];a.cachedgroupIds=[];a.cachedgroupNames=[];a.cachedgroupProperties=[];a.waitinggroupIds=
[];a.waitinggroupNames=[];a.waitinggroupProperties=[];return a}();popup.prototype.room={options:{roomId:0,intervalPing:!1,lastEvent:0,lastMessage:0},init:function(a){var b=this,c;for(c in a)this.options[c]=a[c];$("#sendForm").bind("submit",function(){var a=$("textarea#messageInput").val();0===a.length?dia.error("Please enter your message."):(b.sendMessage(a),$("textarea#messageInput").val(""));return!1});$("#messageInput").onEnter(function(){$("#sendForm").submit();return!1});fimApi.getRooms({id:this.options.roomId},{each:function(a){a.permissions.view?a.permissions.post?
b.enableSender():(dia.error("You are not allowed to post in this room. You will be able to view it, though."),b.disableSender()):(window.roomId=!1,window.location.hash="#rooms",dia.error("You have been restricted access from this room. Please select a new room."));a.permissions.view&&(window.roomId=a.id,$("#roomName").html(a.name),$("#topic").html(a.topic),b.populateMessages());a.permissions.properties||a.permissions.grant||$("#active-view-room #chatContainer button[name=editRoom]").hide()},exception:function(a){"idNoExist"===
a.string?(window.roomId=!1,window.location.hash="#rooms",dia.error("That room doesn't exist. Please select a room.")):fimApi.getDefaultExceptionHandler()(a)}});fimApi.getActiveUsers({roomIds:[this.options.roomId]},{refresh:15E3,timerId:1,begin:function(){$("#activeUsers").html("<ul></ul>")},each:function(a){$("#activeUsers > ul").append($("<li>").append(fim_buildUsernameTag($("<span>"),a.id,fim_getUsernameDeferred(a.id),!0)))}})},setRoom:function(a){this.options.roomId!=a&&this.init({roomId:a})},
eventListener:function(){var a=new EventSource(directory+"stream.php?queryId="+this.options.roomId+"&streamType=room&lastEvent="+this.options.lastEvent+"&lastMessage="+this.options.lastMessage+"&access_token="+window.sessionHash),b=function(a){var b=this;return function(c){c.id>b.options.lastEvent&&(b.options.lastEvent=c.id);a(JSON.parse(c.data))}};a.addEventListener("newMessage",b(this.newMessageHandler),!1);a.addEventListener("topicChange",b(this.topicChangeHandler),!1);a.addEventListener("deletedMessage",
b(this.deletedMessageHandler),!1);a.addEventListener("editedMessage",b(this.edittedMesageHandler),!1)},newMessageHandler:function(a){this.options.lastMessage=Math.max(this.options.lastMessage,a.id);fim_newMessage(this.options.roomId,Number(a.id),fim_messageFormat(a,"list"))},deletedMessageHandler:function(a){$("#message"+a.id).fadeOut()},topicChangeHandler:function(a){$("#topic").html(a.param1);console.log("Event (Topic Change): "+a.param1)},editedMessageHandler:function(a){0<$("#message"+a.id).length&&
(a.userId=$("#message"+a.id+" .userName").attr("data-userid"),a.time=$("#message"+a.id+" .messageText").attr("data-time"),fim_newMessage(this.options.roomId,Number(a.id),fim_messageFormat(a,"list")))},getMessagesFromFallback:function(){var a=this;this.options.roomId?fimApi.getEventsFallback({streamType:"room",queryId:this.options.roomId,lastEvent:this.options.lastEvent},{each:function(b){Number(b.id)>Number(a.options.lastEvent)&&(a.options.lastEvent=b.id);"newMessage"==b.eventName&&a.newMessageHandler(b.data)},
end:function(){window.requestSettings.serverSentEvents?a.eventListener():window.setTimeout(function(){a.getMessagesFromFallback()},3E3)}}):console.log("Not requesting messages; room undefined.");return!1},populateMessages:function(){var a=this;$(document).ready(function(){$("#messageList").html("");window.requestSettings[a.options.roomId]={lastMessage:null,firstRequest:!0};messageIndex[a.options.roomId]=[];a.options.roomId?fimApi.getMessages({roomId:a.options.roomId},{each:function(b){fim_newMessage(Number(a.options.roomId),
Number(b.id),fim_messageFormat(b,"list"))},end:function(){window.requestSettings.serverSentEvents?a.eventListener():a.getMessagesFromFallback()}}):console.log("Not requesting messages; room undefined.");a.options.intervalPing&&clearInterval(a.options.intervalPing);fimApi.ping(a.options.roomId);a.options.intervalPing=window.setInterval(function(){fimApi.ping(a.options.roomId)},3E5);windowDraw()})},sendMessage:function(a,b,c){this.options.roomId?fimApi.sendMessage(this.options.roomId,{ignoreBlock:1===
b?1:"",message:a,flag:c?c:""},{end:function(a){"censor"in a&&0<Object.keys(a.censor).length&&dia.info(Object.values(a.censor).join("<br /><br />"),"Censor warning: "+Object.keys(a.censor).join(", "))},exception:function(b){"confirmCensor"===b.string?dia.confirm({text:b.details,"true":function(){this.sendMessage(a,1,c)}},"Censor Warning"):"spaceMessage"===b.string?dia.error("Too... many... spaces!"):fimApi.getDefaultExceptionHandler()(b)},error:function(b){window.settings.reversePostOrder?$("#messageList").append('Your message, "'+
a+'", could not be sent and will be retried.'):$("#messageList").prepend('Your message, "'+a+'", could not be sent and will be retried.');window.setTimeout(function(){this.sendMessage(a)},5E3);return!1}}):window.location.hash="#rooms"},disableSender:function(){$("#messageInput").attr("disabled","disabled");$("#icon_url").button({disabled:!0});$("#icon_submit").button({disabled:!0});$("#icon_reset").button({disabled:!0})},enableSender:function(){$("#messageInput").removeAttr("disabled");$("#icon_url").button({disabled:!1});
$("#icon_submit").button({disabled:!1});$("#icon_reset").button({disabled:!1})}};popup.prototype.rooms={options:{roomNameSearch:null,page:null,permFilter:null},entryTemplate:Handlebars.compile($("#view-rooms-row").html()),init:function(a){var b=this;this.setPage(0);this.setPermFilter("view");this.setRoomNameSearch("");$("form#roomSearch [name=roomNameSearch], form#roomSearch [name=permFilter]").unbind("change").bind("change",function(){fim_setHashParameter($(this).attr("name"),$(this).val())});$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",
Number(b.options.page)+1)});$("#active-view-rooms button[name=roomListPrev]").unbind("click").bind("click",function(){fim_setHashParameter("page",b.options.page-1)})},setPermFilter:function(a){this.options.permFilter!==a&&(this.options.permFilter=a,$("form#roomSearch [name=permFilter]").val(a))},setRoomNameSearch:function(a){this.options.roomNameSearch!==a&&(this.options.roomNameSearch=a,$("form#roomSearch [name=roomNameSearch]").val(a))},setPage:function(a){this.options.page!==a&&(this.options.page=
a,0>=this.options.page?(this.options.page=0,$("#active-view-rooms button[name=roomListPrev]").attr("disabled",!0)):$("#active-view-rooms button[name=roomListPrev]").removeAttr("disabled"))},retrieve:function(){var a=this;$("#roomTableHtml").html("");fimApi.getRooms(this.options,{each:function(b){$("#roomTableHtml").append(a.entryTemplate(fim_getHandlebarsPhrases(b)))},end:function(a,c){0==Object.keys(a).length?($("#active-view-rooms button[name=roomListNext]").attr("disabled",!0),$("#roomTableHtml").append('<tr><td colspan="3">No Results Found</td></tr>')):
($("#active-view-rooms button[name=roomListNext]").removeAttr("disabled"),$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(c.nextPage))}))}})},update:function(a,b){this.options[a]=b}};
