/*
 Joseph T. Parsons 2017
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");
var autoEntry=function(a,b){this.options=b;var c=this;a.append($("<form>").attr("class","input-group").append($("<span>").attr("class","input-group-btn").append($("<button>").attr({"class":"btn btn-success"}).text("Add")),$("<input>").attr({type:"text",name:this.options.name+"Bridge",id:this.options.name+"Bridge",class:"ui-autocomplete-input form-control",autocomplete:"off"}).autocompleteHelper(this.options.list)).submit(function(){var a=$("input[name="+c.options.name+"Bridge]",this);c.addEntry(a.attr("data-id"),
a.val());a.val("");return!1}));$('<input type="hidden" name="'+this.options.name+'" id="'+this.options.name+'">').insertAfter(a);$("<div>").attr("id",this.options.name+"List").insertAfter(a);"default"in b&&this.displayEntries(b.default);return this};
autoEntry.prototype={setOnAdd:function(a){this.options.onAdd=a},addEntry:function(a,b,c){var d=this;if(!a&&b)var e=$.when(this.options.resolveFromNames([b])).then(function(c){a=c[b].id});else!b&&a&&(e=$.when(this.options.resolveFromIds([a]).then(function(c){b=c[a].name})));$.when(e).then(function(){if(a)if($("span #"+d.options.name+"SubList"+a).length)dia.info("Duplicate entry."),$("#"+d.options.name+"Bridge").val("");else{var e=$("<span>");"allowedUsers"==d.options.name||"moderators"==d.options.name?
e=fim_buildUsernameTag(e,a,fim_getUsernameDeferred(a),!0):e.text(b);$("#"+d.options.name).val($("#"+d.options.name).val()+","+a);$("#"+d.options.name+"List").append($("<div>").attr({id:d.options.name+"SubList"+a,"class":"input-group input-group-sm m-1",style:"display: inline-block; width: auto; white-space: nowrap"}).append($("<span>").attr({"class":"input-group-btn",style:"display: inline-block; vertical-align: top"}).append($("<button>").attr({type:"button","class":"btn btn-danger"}).text("\u00d7").click(function(){d.removeEntry(a)})),
$("<span>").attr({"class":"input-group-addon",style:"display: inline-block"}).append(e)));if(!c&&d.options.onAdd)d.options.onAdd(a)}else dia.error("Invalid entry.")})},removeEntry:function(a){var b=this.options;$("#"+this.options.name).val($("#"+this.options.name).val().replace(new RegExp("(^|,)"+a+"(,|$)"),"$1$2").replace(/^,|(,),|,$/,"$1"));$("#"+this.options.name+"SubList"+a).fadeOut(500,function(){$(this).remove();if("function"===typeof b.onRemove)b.onRemove(a)})},displayEntries:function(a){var b=
"object"===typeof a?a:"string"===typeof a&&0<a.length?a.split(","):[];var c=this;$.when(this.options.resolveFromIds(b)).then(function(a){for(var d=0;d<b.length;d++)c.addEntry(b[d],a[b[d]].name,!0)})},getList:function(){return $("#"+this.options.name).val().split(",").filter(Number)}};var popup=function(){};
popup.prototype.login=function(){function a(a){$("#modal-login").modal("hide");a.userData.permissions.view?a.userData.permissions.post?dia.info("You are now logged in as "+a.userData.name+".","Logged In"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to post and have been silenced by an administrator. You may still view rooms which allow you access.","Logged In"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to view and have been banned by an administrator.","Logged In")}
function b(a){switch(a.string){case "sessionMismatchUserId":case "sessionMismatchBrowser":case "sessionMismatchIp":case "invalidSession":dia.error("The server rejected the stored session. Please login.");break;case "loginRequired":dia.error("A valid login must be provided. Please login.");break;case "invalid_grant":dia.error("The login provided is not valid. You most likely entered an incorrect password.");break;default:dia.error("Unknown error logging in: "+a.string)}}fim_renderHandlebarsInPlace($("#modals-login"));
$("#modal-login").modal();$("#loginForm").submit(function(){var c=$("#loginForm");standard.initialLogin({username:$("input[name=userName]",c).val(),password:$("input[name=password]",c).val(),finish:a,error:b});return!1});$("#modal-login").on("hide.bs.modal",function(){window.userId||standard.initialLogin({grantType:"anonymous",rememberMe:!1,finish:a,error:b})})};
popup.prototype.viewStats=function(){$("#modal-stats").modal();$("table#viewStats > tbody").html("");for(i=1;10>=i;i+=1)$("table#viewStats > tbody").append("<tr><th>"+i+"</th></tr>");fimApi.getStats({roomId:window.roomId},{each:function(a){$("table#viewStats > thead > tr").append($("<th>").append($("<span>").attr({"class":"roomName","data-roomId":a.id}).text(a.name)));var b=0;jQuery.each(a.users,function(a,d){$("table#viewStats > tbody > tr").eq(b).append($("<td>").append(fim_buildUsernameTag($("<span>"),
d.id,fim_getUsernameDeferred(d.id),!0),$("<span>").text("("+d.messageCount+")")));b++})}})};
popup.prototype.settings={init:function(){var a={disableFormatting:16,disableImage:32,disableVideos:64,reversePostOrder:1024,showAvatars:2048,audioDing:8192,disableFx:262144,disableRightClick:1048576,usTime:16777216,twelveHourTime:33554432,webkitNotifications:536870912};fimApi.getUsers({info:["self","profile"],id:userId},{each:function(a){console.log(a);var b=[];b={r:0,g:0,b:0};var d=[];d={r:0,g:0,b:0};new autoEntry($("#changeSettingsForm [name=ignoreListContainer]"),{name:"ignoreList","default":a.ignoredUsers,
list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});new autoEntry($("#changeSettingsForm [name=friendsListContainer]"),{name:"friendsList","default":a.friendedUsers,list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});new autoEntry($("#changeSettingsForm [name=watchRoomsContainer]"),{name:"watchRooms","default":a.watchRooms,list:"rooms",resolveFromIds:Resolver.resolveRoomsFromIds,resolveFromNames:Resolver.resolveRoomsFromNames});
$("#fontPreview").attr("style",a.messageFormatting);defaultFormatting=a.messageFormatting.split(";");defaultFormattingObj={};jQuery.each(defaultFormatting,function(a,b){pair=b.split(":");defaultFormattingObj[pair[0]]=pair[1]});a.profile&&$("#profile").val(a.profile);"font-weight"in defaultFormattingObj&&"bold"==defaultFormattingObj["font-weight"]&&($("#fontPreview").css("font-weight","bold"),$("#defaultBold").attr("checked","checked"));$("#defaultBold").change(function(){$("#defaultBold").is(":checked")?
$("#fontPreview").css("font-weight","bold"):$("#fontPreview").css("font-weight","normal")});"font-style"in defaultFormattingObj&&"italic"==defaultFormattingObj["font-style"]&&$("#defaultItalics").attr("checked","checked");$("#defaultItalics").change(function(){$("#defaultItalics").is(":checked")?$("#fontPreview").css("font-style","italic"):$("#fontPreview").css("font-style","normal")});window.serverSettings.formatting.fonts?(jQuery.each(window.serverSettings.formatting.fonts,function(a,b){$("#defaultFace").append($("<option>").attr({value:a,
style:"font-family: "+b}).attr(defaultFormattingObj["font-family"]==b?{selected:"selected"}:{}).text(a))}),$("#defaultFace").change(function(){$("#fontPreview").css("fontFamily",$("#defaultFace > option:selected").attr("data-font"))})):$("#defaultFace").hide();window.serverSettings.formatting.color?("color"in defaultFormattingObj&&($("#defaultColour").css("background-color",defaultFormattingObj.color),d=defaultFormattingObj.color.slice(4,-1).split(","),d={r:d[0],g:d[1],b:d[2]}),$("#defaultColour").ColorPicker({color:d,
onShow:function(a){$(a).fadeIn(500)},onHide:function(a){$(a).fadeOut(500)},onChange:function(a,b,c){defaultColour=c.r+","+c.g+","+c.b;$("#defaultColour").css("background-color","rgb("+defaultColour+")");$("#fontPreview").css("color","rgb("+defaultColour+")")}})):$("#defaultColour").hide();window.serverSettings.formatting.highlight?("background-color"in defaultFormattingObj&&($("#defaultHighlight").css("background-color",defaultFormattingObj["background-color"]),b=defaultFormattingObj["background-color"].slice(4,
-1).split(","),b={r:b[0],g:b[1],b:b[2]}),$("#defaultHighlight").ColorPicker({color:b,onShow:function(a){$(a).fadeIn(500)},onHide:function(a){$(a).fadeOut(500)},onChange:function(a,b,c){defaultHighlight=c.r+","+c.g+","+c.b;$("#defaultHighlight").css("background-color","rgb("+defaultHighlight+")");$("#fontPreview").css("background-color","rgb("+defaultHighlight+")")}})):$("#defaultHighlight").hide();fimApi.getRooms({roomIds:[a.defaultRoomId]},{each:function(a){$("#defaultRoom").val(a.name).attr("data-id",
a.id)}});jQuery.each(a.parentalFlags,function(a,b){$("input[name=parentalFlags][value="+b+"]").attr("checked",!0)});$('input[name=privacyLevel][value="'+a.privacyLevel+'"]').prop("checked",!0)}});"vanilla"!==window.serverSettings.branding.forumType&&$("#settings5profile").hide(0);$("#defaultRoom").autocompleteHelper("rooms");window.webproDisplay.theme&&$('#theme > option[value="'+window.webproDisplay.theme+'"]').attr("selected","selected");$("#theme").change(function(){$("#stylesjQ").attr("href",
"client/css/"+this.value+"/jquery-ui-1.8.16.custom.css");$("#stylesVIM").attr("href","client/css/"+this.value+"/fim.css");$.cookie("webpro_theme",this.value,{expires:14});window.webproDisplay.theme=this.value;return!1});window.webproDisplay.fontSize&&$('#fontsize > option[value="'+window.webproDisplay.fontSize+'"]').attr("selected","selected");$("#fontsize").change(function(){$("body").css("font-size",this.value+"em");$.cookie("webpro_fontsize",this.value,{expires:14});window.webproDisplay.fontSize=
this.value;return!1});snd.volume&&$("#audioVolume").attr("value",100*snd.volume);$("#audioVolume").change(function(){$.cookie("webpro_audioVolume",this.value,{expires:14});snd.volume=this.value/100;return!1});settings.showAvatars&&$("#showAvatars").attr("checked","checked");settings.reversePostOrder&&$("#reversePostOrder").attr("checked","checked");settings.disableFormatting&&$("#disableFormatting").attr("checked","checked");settings.disableVideo&&$("#disableVideo").attr("checked","checked");settings.disableImage&&
$("#disableImage").attr("checked","checked");$("#showAvatars, #reversePostOrder, #disableFormatting, #disableVideo, #disableImage").change(function(){var b=$(this).attr("id");$(this).is(":checked")&&!settings[b]?(settings[b]=!0,$("#messageList").html(""),$.cookie("webpro_settings",Number($.cookie("webpro_settings"))+a[b],{expires:14})):!$(this).is(":checked")&&settings[b]&&(settings[b]=!1,$("#messageList").html(""),$.cookie("webpro_settings",Number($.cookie("webpro_settings"))-a[b],{expires:14}));
standard.changeRoom(window.roomId)});settings.audioDing&&$("#audioDing").attr("checked","checked");settings.disableFx&&$("#disableFx").attr("checked","checked");settings.disableRightClick&&$("#disableRightClick").attr("checked","checked");settings.webkitNotifications&&$("#webkitNotifications").attr("checked","checked");$("#audioDing, #disableFx, #webkitNotifications, #disableRightClick").change(function(){var b=$(this).attr("id");$(this).is(":checked")&&!settings[b]?(settings[b]=!0,$.cookie("webpro_settings",
Number($.cookie("webpro_settings"))+a[b],{expires:14}),"disableFx"===b&&(jQuery.fx.off=!0),"webkitNotifications"===b&&(notify.webkitNotifySupported()?notify.webkitNotifyRequest():dia.error("Notifications are not supported on your browser."))):!$(this).is(":checked")&&settings[b]&&(settings[b]=!1,$.cookie("webpro_settings",Number($.cookie("webpro_settings"))-a[b],{expires:14}),"disableFx"===b&&(jQuery.fx.off=!1))});$("#changeSettingsForm").submit(function(){var a=[];$("#defaultBold").is(":checked")&&
a.push("bold");$("#defaultItalics").is(":checked")&&a.push("italic");fimApi.editUserOptions("edit",{defaultFontface:$("#defaultFace option:selected").val(),defaultFormatting:a,defaultHighlight:"rgba(0, 0, 0, 0)"===$("#fontPreview").css("background-color")?null:$("#fontPreview").css("background-color").slice(4,-1),defaultColor:$("#fontPreview").css("color").slice(4,-1),defaultRoomId:$("#defaultRoom").attr("data-id"),watchRooms:$("#watchRooms").val().split(","),ignoreList:$("#ignoreList").val().split(","),
friendsList:$("#friendsList").val().split(","),profile:$("#profile").val(),parentalAge:$("form#changeSettingsForm select[name=parentalAge] option:selected").val(),parentalFlags:$("form#changeSettingsForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),privacyLevel:$("input[name=privacyLevel]:radio:checked").val()},{each:function(a){console.log(a)},end:function(){dia.info("Your settings have been updated successfully.");$("#changeSettingsDialogue").empty().remove();
$(".colorpicker").empty().remove()},error:function(a){errorsList=[];for(var b=0;b<a.responseJSON.editUserOptions.length;b++)errorsList.push("<li>"+b+": "+a.responseJSON.editUserOptions[b].exception.details+"</li>");dia.error("Some of your settings have been updated. However, the following values were unable to be processed:<ul>"+errorsList.join()+"</ul>")}});window.history.back();return!1});return!1}};
popup.prototype.uploads={init:function(){fimApi.getFiles({userIds:[window.userId]},{each:function(a){for(var b=[],c=0;c<a.parentalFlags.length;c++)a.parentalFlags[c]&&b.push($l("parentalFlags."+a.parentalFlags[c]));$("#viewUploadsBody").append($("<tr>").append($('<td align="center">').append($('<img style="max-width: 200px; max-height: 200px;" />').attr("src",directory+"file.php?"+$.param({sha256hash:a.sha256hash,thumbnailWidth:200,thumbnailHeight:200}))).append("<br />").append($("<span>").text(a.fileName))).append($('<td align="center">').text(a.fileSizeFormatted)).append($('<td align="center">').text($l("parentalAges."+
a.parentalAge)).append("<br />").append(b.join(", "))).append($('<td align="center">').append($("<button>").attr("class","btn btn-primary").click(function(){fimApi.editUserOptions("edit",{avatar:serverSettings.installUrl+"file.php?sha256hash="+a.sha256hash+"&thumbnailWidth=200&thumbnailHeight=200"},{end:function(a){"avatar"in a?dia.error(a.avatar.string):dia.info("Your avatar has been updated. It will not appear in your old messages.")}})}).text($l("uploads.setToAvatar")).prepend($('<i class="fa fa-picture-o" aria-hidden="true"></i> ')))))}})}};
popup.prototype.editRoom={options:{roomId:0},setOptions:function(a){for(i in a)this.options[i]=a[i]},init:function(a){var b=this;this.setOptions(a);var c=0!=this.options.roomId?"edit":"create";$("#editRoomForm input[name=allowPosting]").change(function(){$(this).is(":checked")?$(this).closest("fieldset").attr("disabled","disabled"):$(this).closest("fieldset").removeAttr("disabled","disabled")});moderatorsList=new autoEntry($("#moderatorsContainer"),{name:"moderators",list:"users",onAdd:function(a){"edit"===
c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post","moderate","properties","grant"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post"])},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});allowedUsersList=new autoEntry($("#allowedUsersContainer"),{name:"allowedUsers",list:"users",onAdd:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,a,["post"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionUser(b.options.roomId,
a,[""])},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});allowedGroupsList=new autoEntry($("#allowedGroupsContainer"),{name:"allowedGroups",list:"groups",onAdd:function(a){"edit"===c&&fimApi.editRoomPermissionGroup(b.options.roomId,a,["post"])},onRemove:function(a){"edit"===c&&fimApi.editRoomPermissionGroup(b.options.roomId,a,[""])},resolveFromIds:Resolver.resolveGroupsFromIds,resolveFromNames:Resolver.resolveGroupsFromNames});fimApi.getCensorLists({roomId:0!=
this.options.roomId?this.options.roomId:null,includeWords:0},{each:function(a){if(a.status)var b=a.status;else if("white"===a.listType)b="block";else if("black"===a.listType)b="unblock";else throw"Bad logic.";$("#editRoomForm [name=censorLists]").append($("<label>").attr("class","btn btn-secondary m-1").text(a.listName).prepend($("<input>").attr({type:"checkbox",name:"censorLists",value:a.listId}).attr(a.listOptions&2?{disabled:"disabled"}:{}).attr("block"==b?{checked:"checked"}:{})))}});0!=this.options.roomId&&
fimApi.getRooms({id:this.options.roomId},{each:function(a){var b=[],c=[];jQuery.each(a.userPermissions,function(a,d){d.moderate&&d.properties&&d.grant?c.push(a):d.post&&b.push(a)});allowedUsersList.displayEntries(b);moderatorsList.displayEntries(c);var d=[];jQuery.each(a.groupPermissions,function(a,b){b.post&&d.push(a)});allowedGroupsList.displayEntries(d);"view"in a.defaultPermissions&&$("#editRoomForm input[name=allowViewing]").prop("checked",!0);"post"in a.defaultPermissions&&$("#editRoomForm input[name=allowPosting]").prop("checked",
!0);$("#editRoomForm input[name=name]").val(a.name);$("#editRoomForm input[name=official]").prop("checked",a.official);$("#editRoomForm input[name=hidden]").prop("checked",a.hidden);jQuery.each(a.parentalFlags,function(a,b){$("#editRoomForm input[name=parentalFlags][value="+b+"]").prop("checked",!0)});$("#editRoomForm select[name=parentalAge] option[value="+a.parentalAge+"]").attr("selected","selected")}});$("#editRoomForm").submit(function(){var a={},e={};"create"===c&&(allowedUsersList.getList().forEach(function(b){a["+"+
b]=["view","post"]}),moderatorsList.getList().forEach(function(b){a["+"+b]=["view","post","moderate"]}),allowedGroupsList.getList().forEach(function(a){e["+"+a]=["post"]}));defaultPermissions=[];$("#editRoomForm input[name=allowViewing]").is(":checked")&&defaultPermissions.push("view");$("#editRoomForm input[name=allowPosting]").is(":checked")&&defaultPermissions.push("post");fimApi.editRoom(b.options.roomId,c,{name:$("#editRoomForm input[name=name]").val(),defaultPermissions:defaultPermissions,userPermissions:a,
groupPermissions:e,parentalAge:$("#editRoomForm select[name=parentalAge] option:selected").val(),parentalFlags:$("#editRoomForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),censorLists:$("#editRoomForm input[name=censorLists]:checked").map(function(){return $(this).attr("value")}).get(),official:$("#editRoomForm input[name=official]").is(":checked"),hidden:$("#editRoomForm input[name=hidden]").is(":checked")},{end:function(a){window.location.hash="#";dia.full({content:$l("editRoom.finish."+
c+"Title")+'<br /><br /><form action="#room='+a.id+'"><div class="input-group"><input autofocus type="text" value="'+currentLocation+"#room="+a.id+'" name="url" class="form-control"  /><span class="input-group-btn"><button class="btn btn-primary">Go!</button></span></div></form>',title:$l("editRoom.finish."+c+"Message"),buttons:{Open:function(){window.location.hash="#room="+a.id},Okay:function(){}}})}});return!1});return!1}};
popup.prototype.online=function(){$("#modal-online").modal();fimApi.getActiveUsers({},{refresh:6E4,begin:function(){$("#onlineUsers").html("")},each:function(a){var b=[];jQuery.each(a.rooms,function(a,d){b.length&&b.push($("<span>").text(", "));b.push(fim_buildRoomNameTag($("<span>"),d.id,fim_getRoomNameDeferred(d.id)))});$("#onlineUsers").append($("<tr>").append($("<td>").append(fim_buildUsernameTag($("<span>"),a.id,fim_getUsernameDeferred(a.id),!0))).append($("<td>").append(b)))}});$("#modal-online").on("hidden.bs.modal",
function(){fimApi.getActiveUsers({},{close:!0})})};
popup.prototype.kicks={dateOptions:{year:"numeric",month:"numeric",day:"numeric",hour:"numeric",minute:"numeric",second:"numeric"},init:function(){fimApi.getKicks(params,{each:function(a){jQuery.each(a.kicks,function(b,c){console.log(c);$("#kickedUsers").append($("<tr>").append($("<td>").append($('<span class="userName userNameTable">').attr({"data-userId":a.userId,style:a.userNameFormat}).text(a.userName))).append($("<td>").append($('<span class="userName userNameTable">').attr({"data-userId":c.kickerId,style:c.kickerNameFormat}).text(c.kickerName))).append($("<td>").append($('<span class="roomName roomNameTable">').attr({"data-roomId":c.roomId}).text(c.roomName))).append($("<td>").text(fim_dateFormat(c.set,
dateOptions))).append($("<td>").text(fim_dateFormat(c.expires,dateOptions))).append($("<td>").append($("<button>").click(function(){standard.unkick(a.userId,c.roomId)}).text("Unkick"))))})}})}};
popup.prototype.kick=function(){$("#modal-kick").modal();$("#userName").autocompleteHelper("users");$("#roomNameKick").autocompleteHelper("rooms");$("#kickUserForm").submit(function(){var a=$("#kickUserForm > #userName").val(),b=$("#kickUserForm > #userName").attr("data-id"),c=$("#kickUserForm > #roomNameKick").val(),d=$("#kickUserForm > #roomNameKick").attr("data-id"),e=Math.floor(Number($("#kickUserForm > #time").val()*Number($("#kickUserForm > #interval > option:selected").attr("value")))),f=!0,
g=!0;c&&!d&&(f=$.when(Resolver.resolveUsersFromNames([a]).then(function(c){b=c[a].id})));c&&!d&&(g=$.when(Resolver.resolveRoomsFromNames([c]).then(function(a){d=a[c].id})));$.when(f,g).then(function(){standard.kick(b,d,e)});return!1});return!1};
popup.prototype.archive={options:{searchText:"",resultLimit:40,searchUser:0,firstMessage:null,page:0,roomId:0},messageData:{},init:function(a){var b=this;for(i in a)this.options[i]=a[i];this.options.roomId||(this.options.roomId=window.roomId);$("#active-view-archive form#archiveSearch input[name=searchText]").unbind("change").bind("change",function(){b.update("searchText",$(this).val());b.retrieve()});$("#active-view-archive form#archiveSearch input[name=searchUser]").unbind("change").bind("change",
function(){console.log("search user",$(this).attr("data-id"));b.update("searchUser",$(this).attr("data-id"));b.retrieve()}).autocompleteHelper("users");$("#active-view-archive button[name=archiveNext]").unbind("click").bind("click",function(){b.nextPage()});$("#active-view-archive button[name=archivePrev]").unbind("click").bind("click",function(){b.prevPage()});$("#active-view-archive button[name=export]").unbind("click").bind("click",function(){popup.exportArchive()});b.retrieve()},setRoom:function(a){this.options.roomId!=
a&&(this.options.roomId=a,this.retrieve())},setFirstMessage:function(a){this.options.firstMessage=a;this.options.lastMessage=null;this.retrieve()},setLastMessage:function(a){this.options.lastMessage=a;this.options.firstMessage=null;this.retrieve()},nextPage:function(){fim_atomicRemoveHashParameterSetHashParameter("firstMessage","lastMessage",$("#active-view-archive table.messageTable tr:last-child > td > span.messageText").attr("data-messageid"))},prevPage:function(){fim_atomicRemoveHashParameterSetHashParameter("lastMessage",
"firstMessage",$("#active-view-archive table.messageTable tr:first-child > td > span.messageText").attr("data-messageid"))},retrieve:function(){var a=this;fimApi.getMessages({roomId:a.options.roomId,userIds:[a.options.searchUser],messageTextSearch:a.options.searchText,messageIdStart:a.options.firstMessage,messageIdEnd:a.options.lastMessage,archive:1,page:a.options.page},{reverseEach:a.options.firstMessage?!0:!1,end:function(b){$("#active-view-archive table.messageTable > tbody").html("");$("#active-view-archive button[name=archivePrev]").prop("disabled",
!1);this.messageData={};jQuery.each(b,function(b,d){$("#active-view-archive table.messageTable > tbody").append(fim_messageFormat(d,"table").append($("<td>").append($('<a href="#archive#room='+a.options.roomId+"#lastMessage="+d.id+'">Show</a>'))));a.messageData[d.id]=d});2>b.length?(a.options.firstMessage&&$("#active-view-archive button[name=archivePrev]").prop("disabled",!0),a.options.lastMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",!0)):(a.options.firstMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",
!1),a.options.lastMessage&&$("#active-view-archive button[name=archivePage]").prop("disabled",!1))}})},update:function(a,b){this.options[a]=b}};
popup.prototype.exportArchive=function(){dia.full({id:"exportDia",content:'<form method="post" action="#" onsubmit="return false;" id="exportDiaForm">How would you like to export the data?<br /><br /><table align="center"><tr><td>Format</td><td><select id="exportFormat"><option value="bbcodetable">BBCode Table</option><option value="csv">CSV List (Excel, etc.)</option></select></td></tr><tr><td colspan="2" align="center"><button type="submit">Export</button></td></tr></table></form>',width:600});
$("#exportDiaForm").submit(function(){switch($("#exportFormat option:selected").val()){case "bbcodetable":var a="";$("#archiveMessageList").find("tr").each(function(){var b=$(this).find("td:eq(0) .userNameTable").text(),c=$(this).find("td:eq(1)").text(),d=$(this).find("td:eq(2)").text();for(i in[0,2]){switch(i){case 0:var e=b;break;case 2:e=d}var f=$(this).find("td:eq("+i+") > span"),g=f.css("color"),l=f.css("backgroundColor"),h=f.css("fontFamily"),k="bold"==f.css("fontWeight")?!0:!1,m="underline"==
f.css("textDecoration")?!0:!1;f="line-through"==f.css("textDecoration")?!0:!1;if(g||l||h)b='[span="'+(g?"color: "+g+";":"")+(l?"background-color: "+l+";":"")+(h?"font: "+h+";":"")+'"]'+b+"[/span]";k&&(b="[b]"+b+"[/b]");m&&(b="[u]"+b+"[/u]");f&&(b="[s]"+b+"[/s]");switch(i){case 1:b=e;break;case 3:d=e}}a+=b+"|"+c+"|"+d+"\n"});a='<textarea style="width: 100%; height: 1000px;">[table=head]User|Time|Message\n'+a+"[/table]</textarea>";break;case "csv":a="",$("#archiveMessageList").find("tr").each(function(){var b=
$(this).find("td:nth-child(1) .userNameTable").text(),c=$(this).find("td:nth-child(2)").text(),d=$(this).find("td:nth-child(3)").text();a+="'"+b+"', '"+c+"', '"+d+"'\n"}),a='<textarea style="width: 100%; height: 600px;">'+a+"</textarea>"}dia.full({id:"exportTable",content:a,width:"1000"});return!1})};var standard=function(){this.userId=0;this.anonId=this.sessionHash="";this.activeLogin={};this.lastEvent=0;this.notifications={}};
standard.prototype.initialLogin=function(a){var b=this,c=a.finish;a.finish=function(d){c&&c(d);b.anonId||($.cookie("webpro_username",a.username,{expires:14}),$.cookie("webpro_password",a.password,{expires:14}),fimApi.getUnreadMessages(null,{each:function(a){b.missedMessageHandler(a)}}));window.roomId||(window.roomId=d.userData.defaultRoomId?d.userData.defaultRoomId:1);fim_renderHandlebarsInPlace($("#entry-template"));fim_hashParse()};this.login(a)};
standard.prototype.login=function(a){var b=this;a.start&&a.start();fimApi.login({grant_type:a.grantType,username:a.username,password:a.password,access_token:a.sessionHash,refresh_token:a.refreshToken,client_id:"WebPro"},{end:function(c){"userData"in c?(b.activeLogin=window.activeLogin=c,b.userId=window.userId=c.userData.id,b.anonId=window.anonId=c.userData.anonId):b.activeLogin||(dia.error("The login did not return proper information. The page will reload in 3 seconds..."),setTimeout(function(){location.reload()},
3E3));b.sessionHash=window.sessionHash=c.access_token;fim_removeHashParameter("sessionHash");a.finish&&a.finish(c);c.expires&&c.refresh_token&&($.cookie("webpro_refreshToken",c.refresh_token),setTimeout(function(){b.login({grantType:"refresh_token",refreshToken:c.refresh_token})},1E3*c.expires/2));fimApi.getRooms({roomIds:window.serverSettings.officialRooms.concat(b.activeLogin.userData.favRooms).concat(b.activeLogin.userData.watchRooms)},{begin:function(){$("#navbar div[name=favRoomsList]").html("");
$("#navbar div[name=officialRoomsList]").html("");$("#navbar div[name=watchRoomsList]").html("")},each:function(a){var c=$("<a>").attr({href:"#room="+a.id,"class":"dropdown-item"}).text(a.name);-1!=b.activeLogin.userData.favRooms.indexOf(a.id)&&$("#navbar div[name=favRoomsList]").append(c.clone());-1!=b.activeLogin.userData.watchRooms.indexOf(a.id)&&$("#navbar div[name=watchRoomsList]").append(c.clone());a.official&&$("#navbar div[name=officialRoomsList]").append(c.clone())}});$("#privateRoomForm input[name=userName]").autocompleteHelper("users");
$("#privateRoomForm").submit(function(){var a=$("#privateRoomForm input[name=userName]").val(),c=$("#privateRoomForm input[name=userName]").attr("data-id"),f=function(a){window.location.hash="#room=p"+[b.userId,a].join()};!c&&a?f(c):a?$.when(Resolver.resolveUsersFromNames([a]).then(function(b){f(b[a].id)})):dia.error("Please enter a username.");return!1});b.getEvents();return!1},error:function(b){a.error&&a.error(b);return!1}})};
standard.prototype.getEventsFromFallback=function(){var a=this;fimApi.getEventsFallback({streamType:"user",lastEvent:this.lastEvent},{each:function(b){a.lastEvent=Math.max(Number(b.id),Number(a.lastEvent));"missedMessage"==b.eventName&&a.missedMessageHandler(b.data)},end:function(){window.requestSettings.serverSentEvents?a.eventListener():window.setTimeout(function(){a.getMessagesFromFallback()},3E3)}})};
standard.prototype.getEventsFromStream=function(){var a=this;(new EventSource(directory+"stream.php?streamType=user&lastEvent="+this.lastEvent+"&access_token="+this.sessionHash)).addEventListener("missedMessage",function(b){return function(c){a.lastEvent=Math.max(a.lastEvent,c.id);b.call(a,JSON.parse(c.data))}}(this.missedMessageHandler),!1)};standard.prototype.getEvents=function(){window.requestSettings.serverSentEvents?this.getEventsFromStream():this.getEventsFromFallback()};
standard.prototype.missedMessageHandler=function(a){a.roomId!=window.roomId&&(this.notifications["room"+a.roomId]||(this.notifications["room"+a.roomId]=$.notify({url:"#room="+a.roomId,message:$("<span>").attr({"class":"missedMessage",id:"missedMessage"+a.roomId,"data-roomId":a.roomId}).prop("outerHTML")},{newest_on_top:!0,type:"info",placement:{from:"top",align:"right"},delay:0,animate:{exit:""},onClose:function(){fimApi.markMessageRead(a.roomId)},url_target:"_self"})),$("#missedMessage"+a.roomId.replace(",",
"\\,")).replaceWith($("<span>").text("New message from ").append(fim_buildUsernameTag($("<strong>"),a.senderId,fim_getUsernameDeferred(a.senderId),!0)).append(" has been made in ").append(fim_buildRoomNameTag($("<strong>"),a.roomId,fim_getRoomNameDeferred(a.roomId))).append(a.missedMessages?$("<span>").text("(Total unread messages: "+a.missedMessages+")"):"")))};
standard.prototype.logout=function(){$.cookie("webpro_username",null);$.cookie("webpro_password",null);$.cookie("webpro_refreshToken",null);fimApi.getMessages(null,{close:!0});fimApi.getActiveUsers(null,{close:!0});fimApi.getUnreadMessages(null,{close:!0});$("#logout").parent().show();$("#login").parent().hide();window.popup.login()};var fimApi=function(a){var b=this;this.directory=a;this.lastSessionHash="";this.requestDefaults={close:!1,timerId:1,refresh:!1,timeout:5E3,cache:!1,begin:function(){},error:function(){},exception:function(){},each:function(){},reverseEach:!1,end:function(){},async:!0,action:null};this.timers={};this.done=function(a,b){return function(c){try{var d=c[b?b:Object.keys(c)[0]];a.begin(d);a.reverseEach&&(d=d.reverse());$.each(d,function(b,c){a.each(c)});a.end(d,c.metadata)}catch(g){console.log("Failed to parse information: "+
c)}}};this.fail=function(a,b){return function(b){!("responseJSON"in b)&&"responseText"in b&&"{"===b.responseText.slice(0,1)&&(b.responseJSON=JSON.parse(b.responseText));if(!("responseJSON"in b))console.log("Unable to parse failure response.");else if("exception"in b.responseJSON&&(console.log("Server Exception",JSON.stringify(b.responseJSON)),"The access token provided has expired"!=b.responseJSON.exception.details))return a.exception(b.responseJSON.exception);return a.error(b)}};this.timer=function(a,
d,e){a.close?(console.log("close "+d+"_"+a.timerId,b.timers),clearInterval(b.timers[d+"_"+a.timerId]),delete b.timers[d+"_"+a.timerId]):(e(a),0<a.refresh&&(clearInterval(b.timers[d+"_"+a.timerId]),b.timers[d+"_"+a.timerId]=setInterval(function(){e(a)},a.refresh)))};this.registerDefaultExceptionHandler=function(a){this.requestDefaults.exception=a};this.getDefaultExceptionHandler=function(){return this.requestDefaults.exception};this.mergeDefaults=function(a,b){var c={},d;for(d in a){if(!(d in b))throw"Invalid data in object call: "+
d;null!==a[d]&&void 0!==a[d]&&(c[d]=a[d])}for(d in b)d in c||null===b[d]||(c[d]=b[d]);return c};this.jsonify=function(a,b){a=void 0===a?{}:Object.create(a);for(var c in b)b[c]in a&&(a[b[c]]=JSON.stringify(a[b[c]]));return a}};
fimApi.prototype.login=function(a,b){var c=this;a=this.mergeDefaults(a,{grant_type:"password",username:null,password:null,access_token:null,refresh_token:null,client_id:""});b=this.mergeDefaults(b,this.requestDefaults);return $.ajax({url:this.directory+"validate.php",type:"POST",data:a,timeout:b.timeout,cache:b.cache}).done(function(a){a.login.access_token&&(c.lastSessionHash=a.login.access_token);b.end(a.login)}).fail(function(a){b.error(a.responseJSON.exception)})};
fimApi.prototype.getUsers=function(a,b){var c=this;a=this.mergeDefaults(a,{info:["self","groups","profile"],access_token:this.lastSessionHash,id:null,userIds:null,userNames:null,userNameSearch:null});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/user.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getUsers(a,b)}))};
fimApi.prototype.createUser=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);return $.ajax({type:"post",url:this.directory+"api/user.php",data:this.mergeDefaults(a,{name:null,password:null,birthDate:null,email:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getUsers(a,b)}))};
fimApi.prototype.getRooms=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,id:null,roomIds:null,roomNames:null,roomNameSearch:null,permFilter:null,page:null});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/room.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getRooms(a,b)}))};
fimApi.prototype.getEventsFallback=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);this.timer(b,"getEventsFallback",function(b){$.ajax({type:"get",url:c.directory+"stream.php",data:c.mergeDefaults(a,{fallback:!0,access_token:c.lastSessionHash,streamType:null,queryId:null,lastEvent:null,lastMessage:null}),timeout:b.timeout,cache:b.cache}).done(function(a){c.done(b)(a)}).fail(function(d){b.refresh&&c.getEventsFallback(null,{close:!0});c.fail(b,function(){c.getEventsFallback(a,
b)})(d)})})};fimApi.prototype.getMessages=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);this.timer(b,"getMessages",function(b){$.ajax({type:"get",url:c.directory+"api/message.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash,roomId:null,userIds:null,messageIdEnd:null,messageIdStart:null,page:null,messageTextSearch:null,archive:!1}),timeout:b.timeout,cache:b.cache}).done(c.done(b)).fail(c.fail(b,function(){c.getMessages(a,b)}))})};
fimApi.prototype.sendMessage=function(a,b,c){var d=this;b=this.mergeDefaults(b,{access_token:this.lastSessionHash,ignoreBlock:!1,message:null,flag:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({roomId:a}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.sendMessage(a,b,c)}))};
fimApi.prototype.editMessage=function(a,b,c,d){var e=this;c=this.mergeDefaults(c,{ignoreBlock:!1,message:null,flag:null});d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({_action:"edit",access_token:this.lastSessionHash,id:b,roomId:a}),type:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.editMessage(a,b,c,d)}))};
fimApi.prototype.deleteMessage=function(a,b,c){var d=this;c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({_action:"delete",access_token:this.lastSessionHash,id:b,roomId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.deleteMessage(a,b,c)}))};
fimApi.prototype.getUnreadMessages=function(a,b){var c=this;b=this.mergeDefaults(b,this.mergeDefaults({timeout:3E4,refresh:3E4},this.requestDefaults));fimApi.timer(b,"getUnreadMessages",function(b){$.ajax({type:"get",url:c.directory+"api/unreadMessages.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash}),timeout:b.timeout,cache:b.cache}).done(c.done(b)).fail(function(d){b.refresh&&c.getUnreadMessages(null,{close:!0});c.fail(b,function(){c.getUnreadMessages(a,b)})(d)})})};
fimApi.prototype.getFiles=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,userIds:"",fileIds:""});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/files.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getFiles(a.requestSettings)}))};
fimApi.prototype.getStats=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/stats.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,number:10}),timeout:b.timeout,cache:b.cache}).done(this.done(b,"roomStats")).fail(this.fail(b,function(){c.getStats(a,b)}))};
fimApi.prototype.getKicks=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/kick.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,userId:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getKicks(a,b)}))};
fimApi.prototype.getCensorLists=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,listIds:null,includeWords:1});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/getCensorLists.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getCensorLists(a,b)}))};
fimApi.prototype.getActiveUsers=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);fimApi.timer(b,"getActiveUsers",function(b){$.ajax({type:"get",url:c.directory+"api/userStatus.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash,roomIds:null,userIds:null,onlineThreshold:null}),timeout:b.timeout,cache:b.cache}).done(c.done(b,"users")).fail(function(d){b.refresh&&c.getActiveUsers(null,{close:!0});c.fail(b,function(){c.getActiveUsers(a,b)})(d)})})};
fimApi.prototype.getGroups=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/group.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,groupIds:null,groupNames:null,groupNameSearch:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getGroups(a,b)}))};
fimApi.prototype.acHelper=function(a){var b=this;return function(c,d){$.ajax({type:"get",url:b.directory+"api/acHelper.php",data:{access_token:b.lastSessionHash,list:a,search:c.term},success:function(a){d($.map(a.entries,function(a,b){return{label:a,value:b}}))}})}};
fimApi.prototype.kickUser=function(a,b,c,d){var e=this;d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/kick.php?"+$.param({access_token:this.lastSessionHash,roomId:b,userId:a}),type:"POST",data:{length:c},timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.kickUser(a,b,c,d)}))};
fimApi.prototype.unkickUser=function(a,b,c){var d=this;c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/kick.php?"+$.param({access_token:this.lastSessionHash,_action:"delete",roomId:b,userId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.unkickUser(a,b,c)}))};
fimApi.prototype.markMessageRead=function(a,b){var c=this;params={access_token:this.lastSessionHash,roomId:a};b=this.mergeDefaults(b,this.requestDefaults);$.ajax({url:this.directory+"api/markMessageRead.php",type:"POST",data:params,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.markMessageRead(a,b)}))};
fimApi.prototype.editUserOptions=function(a,b,c){var d=this;b=this.mergeDefaults(b,{defaultFormatting:null,defaultColor:null,defaultHighlight:null,defaultRoomId:null,watchRooms:null,favRooms:null,ignoreList:null,friendsList:null,profile:null,defaultFontface:null,parentalAge:null,parentalFlags:null,avatar:null,privacyLevel:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/userOptions.php?"+$.param({access_token:this.lastSessionHash,_action:a?a:"edit"}),type:"POST",
data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.editUserOptions(a,b,c)}))};fimApi.prototype.favRoom=function(a){this.editUserOptions("create",{favRooms:[a]})};fimApi.prototype.unfavRoom=function(a){this.editUserOptions("delete",{favRooms:[a]})};fimApi.prototype.watchRoom=function(a){this.editUserOptions("create",{watchRooms:[a]})};fimApi.prototype.unwatchRoom=function(a){this.editUserOptions("delete",{watchRooms:[a]})};
fimApi.prototype.editRoom=function(a,b,c,d){var e=this;c=this.mergeDefaults(c,{access_token:this.lastSessionHash,name:null,defaultPermissions:null,userPermissions:null,groupPermissions:null,censorLists:null,parentalAge:null,parentalFlags:null,hidden:null,official:null});d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/room.php?"+$.param(this.mergeDefaults({},{id:a,_action:b})),method:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.editRoom(a,
c,d)}))};fimApi.prototype.createRoom=function(a,b){this.editRoom(null,"create",a,b)};fimApi.prototype.deleteRoom=function(a,b){this.editRoom(a,"delete",{},b)};fimApi.prototype.undeleteRoom=function(a,b){this.editRoom(a,"undelete",{},b)};fimApi.prototype.editRoomPermissionUser=function(a,b,c){var d={};d["*"+b]=c;this.editRoom(a,"edit",{userPermissions:d})};fimApi.prototype.editRoomPermissionGroup=function(a,b,c){var d={};d["*"+b]=c;this.editRoom(a,"edit",{groupPermissions:d})};
fimApi.prototype.editUserStatus=function(a,b,c){var d=this;b=this.mergeDefaults(b,{status:null,typing:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/userStatus.php?"+$.param({_action:"edit",access_token:this.lastSessionHash,roomIds:[a]}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.editUserStatus(a,b,c)}))};fimApi.prototype.ping=function(a,b){this.editUserStatus(a,{status:""},b)};
fimApi.prototype.exitRoom=function(a,b){this.editUserStatus(a,{status:"offline"},b)};fimApi.prototype.startedTyping=function(a,b){this.editUserStatus(a,{typing:!0},b)};fimApi.prototype.stoppedTyping=function(a,b){this.editUserStatus(a,{typing:!1},b)};fimApi.prototype.changeAvatar=function(a,b){this.editUserOptions({avatarHash:a},b)};var Resolver=function(){function a(){}a.cacheEntry=function(b,c){-1===a["cached"+b+"Ids"].indexOf(c.id)&&(a["cached"+b+"Ids"].push(String(c.id)),a["cached"+b+"Names"].push(String(c.name)),a["cached"+b+"Properties"].push(c))};a.resolve=function(b,c,d){var e=$.Deferred(),f={},g=[],l=[],h=c.charAt(0).toUpperCase()+c.slice(1)+"s",k=b+h;if("id"==c)for(h=0;h<d.length;h++)d[h]=String(d[h]);h=function(d){if("id"===c||"name"===c)d=String(d);if(-1!==a["cached"+k].indexOf(d))f[d]=a["cached"+b+"Properties"][a["cached"+
k].indexOf(d)];else if(-1!==a["waiting"+k].indexOf(d)){var e=setInterval(function(){console.log(["resolveWaitRetry",k,d,a["cached"+k]]);-1!==a["cached"+k].indexOf(d)&&(clearInterval(e),f[d]=a["cached"+b+"Properties"][a["cached"+k].indexOf(d)],l.splice($.inArray(d,l),1))},100);l.push(d)}else a["waiting"+k].push(d),g.push(d)};for(var m=0;m<d.length;m++)h(d[m]);0<g.length&&(d={},d[k]=g,fimApi["get"+b.charAt(0).toUpperCase()+b.slice(1)+"s"](d,{each:function(d){a.cacheEntry(b,d);f[d[c]]=d},end:function(){g=
[]}}));if(0<l.length||0<g.length)var n=setInterval(function(){0==l.length&&0==g.length&&(clearInterval(n),e.resolve(f))},100);else e.resolve(f);return e.promise()};a.resolveUsersFromIds=function(b){return a.resolve("user","id",b)};a.resolveUsersFromNames=function(b){return a.resolve("user","name",b)};a.resolveRoomsFromIds=function(b){return a.resolve("room","id",b)};a.resolveRoomsFromNames=function(b){return a.resolve("room","name",b)};a.resolveGroupsFromIds=function(b){return a.resolve("group","id",
b)};a.resolveGroupsFromNames=function(b){return a.resolve("group","name",b)};a.cacheduserIds=[];a.cacheduserNames=[];a.cacheduserProperties=[];a.waitinguserIds=[];a.waitinguserNames=[];a.waitinguserProperties=[];a.cachedroomIds=[];a.cachedroomNames=[];a.cachedroomProperties=[];a.waitingroomIds=[];a.waitingroomNames=[];a.waitingroomProperties=[];a.cachedgroupIds=[];a.cachedgroupNames=[];a.cachedgroupProperties=[];a.waitinggroupIds=[];a.waitinggroupNames=[];a.waitinggroupProperties=[];return a}();popup.prototype.room=function(){this.options={roomId:0,lastEvent:0,lastMessage:0};this.windowBlurred=this.faviconFlashTimer=!1;this.messageIndex=[];this.pingInterval=this.eventTimeout=this.roomSource=this.isTyping=!1};
popup.prototype.room.prototype.insertDoc=function(){$("#modal-insertDoc").modal();var a="",b=0,c=[],d="";"fileUploads"in window.serverSettings?(window.serverSettings.fileUploads.extensionChangesReverse={},jQuery.each(window.serverSettings.fileUploads.extensionChanges,function(a,b){b in window.serverSettings.fileUploads.extensionChangesReverse||(window.serverSettings.fileUploads.extensionChangesReverse[b]=[b]);window.serverSettings.fileUploads.extensionChangesReverse[b].push(b)}),jQuery.each(window.serverSettings.fileUploads.allowedExtensions,
function(a,b){a=window.serverSettings.fileUploads.sizeLimits[b];var c=window.serverSettings.fileUploads.fileContainers[b],d=window.serverSettings.fileUploads.extensionChangesReverse[b];$("table#fileUploadInfo tbody").append("<tr><td>"+(d?d.join(", "):b)+"</td><td>"+$l("fileContainers."+c)+"</td><td>"+$.formatFileSize(a,$l("byteUnits"))+"</td></tr>")}),"function"!==typeof FileReader?$("#uploadFileForm").html($l("uploadErrors.notSupported")):($("#uploadFileForm").submit(function(){var a=$('input#fileUpload[type="file"]').prop("files");
0==a.length?dia.error("Please select a file to upload."):($("#chatContainer").fileupload("add",{files:a}),$("#modal-insertDoc").modal("hide"));return!1}),$("#fileUpload").bind("change",function(){var e=new FileReader,f=new FileReader;console.log("FileReader triggered.");$("#imageUploadSubmitButton").attr("disabled","disabled").button({disabled:!0});0===this.files.length?dia.error("No files selected!"):1<this.files.length?dia.error("Too many files selected!"):(console.log("FileReader started."),a=
this.files[0].name,b=this.files[0].size,c=a.split("."),d=c[c.length-1],d in window.serverSettings.fileUploads.extensionChanges&&(d=window.serverSettings.fileUploads.extensionChanges[d]),-1===$.inArray(d,$.toArray(window.serverSettings.fileUploads.allowedExtensions))?$("#uploadFileFormPreview").html($l("uploadErrors.badExtPersonal")):b>window.serverSettings.fileUploads.sizeLimits[d]?$("#uploadFileFormPreview").html($l("uploadErrors.tooLargePersonal",{fileSize:window.serverSettings.fileUploads.sizeLimits[d]})):
($("#uploadFileFormPreview").html("Loading Preview..."),e.readAsBinaryString(this.files[0]),e.onloadend=function(){window.btoa(e.result)},f.readAsDataURL(this.files[0]),f.onloadend=function(){$("#uploadFileFormPreview").html(fim_messagePreview(window.serverSettings.fileUploads.fileContainers[d],this.result))},$("#imageUploadSubmitButton").removeAttr("disabled").button({disabled:!1})))}))):$("#insertDocUpload").html("Disabled.");return!1};
popup.prototype.room.prototype.newMessage=function(a,b,c){if(!(-1<$.inArray(b,this.messageIndex))){if(0<$("#message"+b).length)$("#message"+b).replaceWith(c);else{var d=!1;$("#messageList .messageLine").each(function(){if(window.settings.reversePostOrder){if($(".messageText",this).attr("data-messageId")<b)return $(c).insertBefore(this),d=!0,!1}else if($(".messageText",this).attr("data-messageId")>b)return $(c).insertBefore(this),d=!0,!1});d||(window.settings.reversePostOrder?$("#messageList").prepend(c):
$("#messageList").append(c))}this.messageIndex.push(b);100<=this.messageIndex.length&&($("#message"+this.messageIndex[0]).remove(),this.messageIndex=this.messageIndex.slice(1,99));window.settings.reversePostOrder||this.toBottom();if(this.windowBlurred){window.settings.audioDing&&window.snd.play();this.faviconFlashStart();if("object"===typeof window.external&&"undefined"!==typeof window.external.msIsSiteMode&&"undefined"!==typeof window.external.msSiteModeActivate)try{window.external.msIsSiteMode()&&
window.external.msSiteModeActivate()}catch(e){}window.notify.webkitNotifySupported()&&window.settings.webkitNotifications&&window.notify.webkitNotify("images/favicon.ico","New Message",$(c).text())}$(".messageLine .messageText, .messageLine .userName, body").unbind("keydown");$(".messageLine .messageText").bind("keydown",function(a){if("contextMenu"===window.restrictFocus)return!0;if(38===a.which)return $(this).parent().prev(".messageLine").children(".messageText").focus(),!1;if(37===a.which||39===
a.which)return $(this).parent().children(".userName").focus(),!1;if(40===a.which)return $(this).parent().next(".messageLine").children(".messageText").focus(),!1});$(".messageLine .userName").bind("keydown",function(a){if("contextMenu"===window.restrictFocus)return!0;if(38===a.which)return $(this).parent().prev(".messageLine").children(".userName").focus(),!1;if(39===a.which||37===a.which)return $(this).parent().children(".messageText").focus(),!1;if(40===a.which)return $(this).parent().next(".messageLine").children(".userName").focus(),
!1})}};popup.prototype.room.prototype.toBottom=function(){$("#messageListContainer").scrollTop($("#messageListContainer")[0].scrollHeight)};popup.prototype.room.prototype.faviconFlashStart=function(){this.faviconFlashTimer=window.setInterval(this.faviconFlashOnce,1E3)};popup.prototype.room.prototype.faviconFlashStop=function(){this.faviconFlashTimer&&(window.clearInterval(this.faviconFlashTimer),this.faviconFlashTimer=!1)};
popup.prototype.room.prototype.faviconFlashOnce=function(){"images/favicon.ico"===$("#favicon").attr("href")?$("#favicon").attr("href","images/favicon2.ico"):$("#favicon").attr("href","images/favicon.ico")};
popup.prototype.room.prototype.onWindowResize=function(){$(window).width();var a=$(window).height();$("#messageListContainer").css("height",Math.floor(a-$("#messageListCardHeader").height()-$("#textentryBoxMessage").height()-$("#navbar").height()-65));$("#activeUsers").css("height",Math.floor(a-$("#activeUsersCardHeader").height()-$("#navbar").height()-65))};
popup.prototype.room.prototype.init=function(a){var b=this,c;for(c in a)this.options[c]=a[c];document.addEventListener("visibilitychange",function(){"hidden"==document.visibilityState?b.windowBlurred=!0:(b.windowBlurred=!1,b.faviconFlashStop())});$(window).on("resize",null,this.onWindowResize);$("#chatContainer").fileupload({dropZone:$("body"),pasteZone:$("textarea#messageInput"),url:window.serverSettings.installUrl+"api/editFile.php?"+$.param({_action:"create",uploadMethod:"put",dataEncode:"binary",
fileName:"pasteupload.png",access_token:window.sessionHash}),type:"PUT",multipart:!1,send:function(a,c){c.url+="&roomId="+b.options.roomId;return!0}});$(document).bind("drop dragover",function(a){a.preventDefault()});$("#sendForm").bind("submit",function(){var a=$("textarea#messageInput").val();0===a.length?dia.error("Please enter your message."):(b.sendMessage(a),$("textarea#messageInput").val(""));return!1});$("textarea#messageInput").onEnter(function(){$("#sendForm").submit();return!1});fimApi.ping(this.options.roomId);
this.pingInterval=window.setInterval(function(){fimApi.editUserStatus(b.options.roomId,{status:"",typing:b.typing})},3E5);$("textarea#messageInput").on("keyup",fim_debounce(function(){fimApi.stoppedTyping(b.options.roomId);b.isTyping=!1},2E3)).on("keydown",function(){b.isTyping||(b.isTyping=!0,fimApi.startedTyping(b.options.roomId))});$(window).on("beforeunload",null,function(){b.beforeUnload(b.options.roomId)});$("textarea#messageInput").mouseup(this.onWindowResize);window.standard.notifications["room"+
this.options.roomId]&&window.standard.notifications["room"+this.options.roomId].close();fimApi.getRooms({id:this.options.roomId},{each:function(a){a.permissions.view?a.permissions.post?b.enableSender():(dia.error("You are not allowed to post in this room. You will be able to view it, though."),b.disableSender()):(window.roomId=!1,window.location.hash="#rooms",dia.error("You have been restricted access from this room. Please select a new room."));a.permissions.view&&(window.roomId=a.id,$("#roomName").html(a.name),
$("#topic").html(a.topic),b.populateMessages());a.permissions.properties||a.permissions.grant||$("#active-view-room #chatContainer button[name=editRoom]").hide()},exception:function(a){"idNoExist"===a.string?(window.roomId=!1,window.location.hash="#rooms",dia.error("That room doesn't exist. Please select a room.")):fimApi.getDefaultExceptionHandler()(a)}});fimApi.getActiveUsers({roomIds:[this.options.roomId]},{refresh:15E3,timerId:1,begin:function(){$("ul#activeUsers").html("")},each:function(a){jQuery.each(a.rooms,
function(c,d){b.userStatusChangeHandler({status:d.status,typing:d.typing,userId:a.id})})}})};popup.prototype.room.prototype.close=function(){fimApi.getActiveUsers({},{timerId:1,close:!0});this.roomSource&&this.roomSource.close();this.eventTimeout&&window.clearTimeout(this.eventTimeout);this.pingInterval&&window.clearInterval(this.pingInterval);$(window).off("beforeunload");this.beforeUnload(this.options.roomId);$(window).off("resize",null,this.onWindowResize)};
popup.prototype.room.prototype.setRoom=function(a){this.options.roomId!=a&&(this.beforeUnload(this.options.roomId),this.init({roomId:a}))};popup.prototype.room.prototype.beforeUnload=function(a){console.log("unload "+a);fimApi.exitRoom(a)};
popup.prototype.room.prototype.eventListener=function(){var a=this;this.roomSource=new EventSource(directory+"stream.php?queryId="+this.options.roomId+"&streamType=room&lastEvent="+this.options.lastEvent+"&lastMessage="+this.options.lastMessage+"&access_token="+window.sessionHash);this.roomSource.onerror=function(){a.roomSource=!1;a.getMessagesFromFallback()};var b=function(b){return function(c){a.options.lastEvent=Math.max(Number(a.options.lastEvent),Number(c.id));b.call(a,JSON.parse(c.data))}};
this.roomSource.addEventListener("userStatusChange",b(this.userStatusChangeHandler),!1);this.roomSource.addEventListener("newMessage",b(this.newMessageHandler),!1);this.roomSource.addEventListener("topicChange",b(this.topicChangeHandler),!1);this.roomSource.addEventListener("deletedMessage",b(this.deletedMessageHandler),!1);this.roomSource.addEventListener("editedMessage",b(this.editedMesageHandler),!1)};
popup.prototype.room.prototype.newMessageHandler=function(a){this.options.lastMessage=Math.max(this.options.lastMessage,a.id);this.newMessage(this.options.roomId,Number(a.id),fim_messageFormat(a,"list"))};popup.prototype.room.prototype.deletedMessageHandler=function(a){$("#message"+a.id).fadeOut()};popup.prototype.room.prototype.topicChangeHandler=function(a){$("#topic").html(a.param1);console.log("Event (Topic Change): "+a.param1)};
popup.prototype.room.prototype.editedMessageHandler=function(a){0<$("#message"+a.id).length&&(a.userId=$("#message"+a.id+" .userName").attr("data-userid"),a.time=$("#message"+a.id+" .messageText").attr("data-time"),this.newMessage(this.options.roomId,Number(a.id),fim_messageFormat(a,"list")))};
popup.prototype.room.prototype.userStatusChangeHandler=function(a){var b=$("ul#activeUsers > li[data-userId="+a.userId+"]"),c=$("<li>").attr("class","list-group-item").attr("data-userId",a.userId).append(fim_buildUsernameTag($("<span>"),a.userId,fim_getUsernameDeferred(a.userId),!0)).append(a.typing?$('<i class="fa fa-keyboard-o" style="vertical-align: middle; margin-left: 10px;"></i>'):$(""));0<b.length?"offline"!==a.status?b.replaceWith(c):b.remove():"offline"!==a.status&&$("ul#activeUsers").append(c)};
popup.prototype.room.prototype.getMessagesFromFallback=function(){var a=this;this.options.roomId?fimApi.getEventsFallback({streamType:"room",queryId:this.options.roomId,lastEvent:this.options.lastEvent},{each:function(b){a.options.lastEvent=Math.max(Number(a.options.lastEvent),Number(b.id));"newMessage"==b.eventName&&a.newMessageHandler(b.data)},end:function(){window.requestSettings.serverSentEvents?a.eventListener():a.eventTimeout=window.setTimeout(function(){a.getMessagesFromFallback()},3E3)}}):
console.log("Not requesting messages; room undefined.");return!1};
popup.prototype.room.prototype.populateMessages=function(){var a=this;$(document).ready(function(){$("#messageList").html("");window.requestSettings[a.options.roomId]={lastMessage:null,firstRequest:!0};a.messageIndex[a.options.roomId]=[];a.options.roomId?fimApi.getMessages({roomId:a.options.roomId},{each:function(b){a.newMessage(Number(a.options.roomId),Number(b.id),fim_messageFormat(b,"list"))},end:function(){window.requestSettings.serverSentEvents?a.eventListener():a.getMessagesFromFallback()}}):
console.log("Not requesting messages; room undefined.");a.onWindowResize()})};
popup.prototype.room.prototype.sendMessage=function(a,b,c){this.options.roomId?fimApi.sendMessage(this.options.roomId,{ignoreBlock:1===b?1:"",message:a,flag:c?c:""},{end:function(a){"censor"in a&&0<Object.keys(a.censor).length&&dia.info(Object.values(a.censor).join("<br /><br />"),"Censor warning: "+Object.keys(a.censor).join(", "))},exception:function(b){"confirmCensor"===b.string?dia.confirm({text:b.details,"true":function(){this.sendMessage(a,1,c)}},"Censor Warning"):"spaceMessage"===b.string?
dia.error("Too... many... spaces!"):fimApi.getDefaultExceptionHandler()(b)},error:function(b){window.settings.reversePostOrder?$("#messageList").append('Your message, "'+a+'", could not be sent and will be retried.'):$("#messageList").prepend('Your message, "'+a+'", could not be sent and will be retried.');window.setTimeout(function(){this.sendMessage(a)},5E3);return!1}}):window.location.hash="#rooms"};
popup.prototype.room.prototype.disableSender=function(){$("#messageInput").attr("disabled","disabled");$("#icon_url").button({disabled:!0});$("#icon_submit").button({disabled:!0});$("#icon_reset").button({disabled:!0})};popup.prototype.room.prototype.enableSender=function(){$("#messageInput").removeAttr("disabled");$("#icon_url").button({disabled:!1});$("#icon_submit").button({disabled:!1});$("#icon_reset").button({disabled:!1})};popup.prototype.rooms={options:{roomNameSearch:null,page:null,permFilter:null},entryTemplate:Handlebars.compile($("#view-rooms-row").html()),init:function(a){var b=this;this.setPage(0);this.setPermFilter("view");this.setRoomNameSearch("");$("form#roomSearch [name=roomNameSearch], form#roomSearch [name=permFilter]").unbind("change").bind("change",function(){fim_setHashParameter($(this).attr("name"),$(this).val())});$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",
Number(b.options.page)+1)});$("#active-view-rooms button[name=roomListPrev]").unbind("click").bind("click",function(){fim_setHashParameter("page",b.options.page-1)})},setPermFilter:function(a){this.options.permFilter!==a&&(this.options.permFilter=a,$("form#roomSearch [name=permFilter]").val(a))},setRoomNameSearch:function(a){this.options.roomNameSearch!==a&&(this.options.roomNameSearch=a,$("form#roomSearch [name=roomNameSearch]").val(a))},setPage:function(a){this.options.page!==a&&(this.options.page=
a,0>=this.options.page?(this.options.page=0,$("#active-view-rooms button[name=roomListPrev]").attr("disabled",!0)):$("#active-view-rooms button[name=roomListPrev]").removeAttr("disabled"))},retrieve:function(){var a=this;$("#roomTableHtml").html("");fimApi.getRooms(this.options,{each:function(b){$("#roomTableHtml").append(a.entryTemplate(fim_getHandlebarsPhrases(b)))},end:function(a,c){0==Object.keys(a).length?($("#active-view-rooms button[name=roomListNext]").attr("disabled",!0),$("#roomTableHtml").append('<tr><td colspan="3">No Results Found</td></tr>')):
($("#active-view-rooms button[name=roomListNext]").removeAttr("disabled"),$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(c.nextPage))}))}})},update:function(a,b){this.options[a]=b}};
