//# sourceMappingURL=fim-all.js.map
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)$jscomp.owns(e,f)&&(a[f]=e[f])}return a}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");var popup=function(){};
popup.prototype.login=function(){function a(a){$("#modal-login").modal("hide");a.userData.permissions.view?a.userData.permissions.post?dia.info("You are now logged in as "+a.userData.name+".","success"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to post and have been silenced by an administrator. You may still view rooms which allow you access.","warning"):dia.info("You are now logged in as "+a.userData.name+". However, you are not allowed to view and have been banned by an administrator.",
"danger")}function b(a){switch(a.string){case "sessionMismatchUserId":case "sessionMismatchBrowser":case "sessionMismatchIp":case "invalidSession":dia.error("The server rejected the stored session. Please login.");break;case "loginRequired":dia.error("A valid login must be provided. Please login.");break;case "invalid_grant":dia.error("The login provided is not valid. You most likely entered an incorrect password.");break;default:dia.error("Unknown error logging in: "+a.string)}}fim_renderHandlebarsInPlace($("#modals-login"));
$("#modal-login").modal();$("#loginForm").submit(function(){var c=$("#loginForm");standard.initialLogin({username:$("input[name=userName]",c).val(),password:$("input[name=password]",c).val(),finish:a,error:b});return!1});$("#modal-login").on("hide.bs.modal",function(){window.userId||standard.initialLogin({grantType:"anonymous",rememberMe:!1,finish:a,error:b})})};
popup.prototype.viewStats=function(){$("#modal-stats").modal();$("table#viewStats > tbody").html("");for(i=1;10>=i;i+=1)$("table#viewStats > tbody").append("<tr><th>"+i+"</th></tr>");fimApi.getStats({roomId:window.roomId},{each:function(a){$("table#viewStats > thead > tr").append($("<th>").append($("<span>").attr({"class":"roomName","data-roomId":a.id}).text(a.name)));var b=0;jQuery.each(a.users,function(a,d){$("table#viewStats > tbody > tr").eq(b).append($("<td>").append(fim_buildUsernameTag($("<span>"),
d.id),$("<span>").text("("+d.messageCount+")")));b++})}})};
popup.prototype.online=function(){$("#modal-online").modal();fimApi.getActiveUsers({},{refresh:6E4,begin:function(){$("#onlineUsers").html("")},each:function(a){var b=[];jQuery.each(a.rooms,function(a,d){b.length&&b.push($("<span>").text(", "));b.push(fim_buildRoomNameTag($("<span>"),d.id))});$("#onlineUsers").append($("<tr>").append($("<td>").append(fim_buildUsernameTag($("<span>"),a.id))).append($("<td>").append(b)))}});$("#modal-online").on("hidden.bs.modal",function(){fimApi.getActiveUsers({},
{close:!0})})};
popup.prototype.kick=function(a,b){$("#modal-kick").modal();$("#kickUserForm input[name=userName]").autocompleteHelper("users",a);$("#kickUserForm input[name=roomName]").autocompleteHelper("rooms",b);$("#kickUserForm").off("submit").on("submit",function(){var a=$("#kickUserForm input[name=userName]").attr("data-id"),b=$("#kickUserForm input[name=roomName]").attr("data-id"),e=Math.floor(Number($("#kickUserForm input[name=time]").val()*Number($("#kickUserForm select[name=interval] > option:selected").attr("value"))));b?
a?fimApi.kickUser(a,b,e,{end:function(){dia.info("The user has been kicked.","success");$("#modal-kick").modal("hide")}}):dia.error("An invalid user was provided."):dia.error("An invalid room was provided.");return!1});return!1};popup.prototype.uploads=function(){this.options={page:null,userId:window.userId};this.entryTemplate=Handlebars.compile($("#view-uploads-row").html())};
popup.prototype.uploads.prototype.init=function(a){var b=this;this.setPage(0);$("#active-view-uploads button[name=nextPage]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(b.options.page)+1)});$("#active-view-uploads button[name=prevPage]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(b.options.page)-1)})};
popup.prototype.uploads.prototype.setPage=function(a){this.options.page!==a&&(console.log("set page 2",a,this.options),this.options.page=a,0>=this.options.page?(console.log("zero page",a),this.options.page=0,$("#active-view-uploads button[name=prevPage]").attr("disabled",!0)):$("#active-view-uploads button[name=prevPage]").removeAttr("disabled"))};popup.prototype.uploads.prototype.setUser=function(a){a?this.options.roomId!==a&&(this.options.userId=a):this.options.userId=null};
popup.prototype.uploads.prototype.retrieve=function(){var a=this;$("#active-view-uploads input[name=user]").autocompleteHelper("users",this.options.userId).off("autocompleteChange").on("autocompleteChange",function(){fim_setHashParameter("user",$(this).attr("data-id"))});$("#uploadsTableBody").html("");fimApi.getFiles({userIds:[this.options.userId],page:this.options.page},{each:function(b){var c=$("<span>"),d=fim_buildUsernameTagPromise(c,b.userId,fim_getUsernameDeferred(b.userId)),e=$("<span>"),
f=fim_buildRoomNameTagPromise(e,b.roomId,fim_getRoomNameDeferred(b.roomId));$.when(d,f).then(function(){$("#uploadsTableBody").append(a.entryTemplate(fim_getHandlebarsPhrases({fileData:b,userTag:c,roomTag:e})))})},end:function(a,c){0==Object.keys(a).length?($("#active-view-uploads button[name=nextPage]").attr("disabled",!0),$("#uploadsTableBody").html(Handlebars.compile($("#view-uploads-emptyResultSet").html())(fim_getHandlebarsPhrases()))):$("#active-view-uploads button[name=nextPage]").removeAttr("disabled")}})};popup.prototype.archive={options:{searchText:"",resultLimit:40,searchUser:0,firstMessage:null,page:0,roomId:0},messageData:{},init:function(a){var b=this;for(i in a)this.options[i]=a[i];$("#active-view-archive form#archiveSearch input[name=searchText]").unbind("change").bind("change",function(){b.update("searchText",$(b).val());b.retrieve()});$("#active-view-archive form#archiveSearch input[name=searchUser]").unbind("change").bind("change",function(){b.update("searchUser",$(b).attr("data-id"));b.retrieve()}).autocompleteHelper("users");
$("#active-view-archive button[name=archiveNext]").unbind("click").bind("click",function(){b.nextPage()});$("#active-view-archive button[name=archivePrev]").unbind("click").bind("click",function(){b.prevPage()});$("#active-view-archive button[name=export]").unbind("click").bind("click",function(){popup.exportArchive()});this.retrieve()},setRoom:function(a){this.options.roomId!=a&&(this.options.roomId=a,this.retrieve())},setFirstMessage:function(a){this.options.firstMessage=a;this.options.lastMessage=
null;this.retrieve()},setLastMessage:function(a){this.options.lastMessage=a;this.options.firstMessage=null;this.retrieve()},nextPage:function(){fim_atomicRemoveHashParameterSetHashParameter("firstMessage","lastMessage",$("#active-view-archive table.messageTable tr:last-child > td > span.messageText").attr("data-messageid"))},prevPage:function(){fim_atomicRemoveHashParameterSetHashParameter("lastMessage","firstMessage",$("#active-view-archive table.messageTable tr:first-child > td > span.messageText").attr("data-messageid"))},
retrieve:function(){var a=this;fimApi.getMessages({roomId:this.options.roomId,userIds:[this.options.searchUser],messageTextSearch:this.options.searchText,messageIdStart:this.options.firstMessage,messageIdEnd:this.options.lastMessage,page:this.options.page},{reverseEach:this.options.firstMessage?!0:!1,end:function(b){$("#active-view-archive table.messageTable > tbody").html("");$("#active-view-archive button[name=archivePrev]").prop("disabled",!1);a.messageData={};jQuery.each(b,function(b,d){b=fim_getUsernameDeferred(d.userId);
$("#active-view-archive table.messageTable > tbody").append($('<tr style="word-wrap: break-word;">').attr({id:"archiveMessage"+d.id}).append($("<td>").append(fim_buildUsernameTag($('<span class="userName userNameTable"></span>'),d.userId,b,d.anonId)),$('<td class="d-none d-sm-table-cell">').text(fim_dateFormat(d.time)),$("<td>").append(fim_buildMessageLine(d.text,d.flag,d.id,Number(d.userId),a.options.roomId,d.time,b)),$('<td class="d-none d-md-table-cell">').append($('<a href="#archive#room='+a.options.roomId+
"#lastMessage="+d.id+'">Show</a>'))));a.messageData[d.id]=d});2>b.length?(a.options.firstMessage&&$("#active-view-archive button[name=archivePrev]").prop("disabled",!0),a.options.lastMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",!0)):(a.options.firstMessage&&$("#active-view-archive button[name=archiveNext]").prop("disabled",!1),a.options.lastMessage&&$("#active-view-archive button[name=archivePage]").prop("disabled",!1))}})},update:function(a,b){this.options[a]=b}};popup.prototype.rooms=function(){this.options={roomNameSearch:null,page:null,permFilter:null};this.entryTemplate=Handlebars.compile($("#view-rooms-row").html())};
popup.prototype.rooms.prototype.init=function(a){var b=this;this.setPage(0);this.setPermFilter("view");this.setRoomNameSearch("");$("form#roomSearch [name=roomNameSearch], form#roomSearch [name=permFilter]").unbind("change").bind("change",function(){fim_setHashParameter($(this).attr("name"),$(this).val())});$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(b.options.page)+1)});$("#active-view-rooms button[name=roomListPrev]").unbind("click").bind("click",
function(){fim_setHashParameter("page",b.options.page-1)})};popup.prototype.rooms.prototype.setPermFilter=function(a){this.options.permFilter!==a&&(this.options.permFilter=a,$("form#roomSearch [name=permFilter]").val(a))};popup.prototype.rooms.prototype.setRoomNameSearch=function(a){this.options.roomNameSearch!==a&&(this.options.roomNameSearch=a,$("form#roomSearch [name=roomNameSearch]").val(a))};
popup.prototype.rooms.prototype.setPage=function(a){this.options.page!==a&&(this.options.page=a,0>=this.options.page?(this.options.page=0,$("#active-view-rooms button[name=roomListPrev]").attr("disabled",!0)):$("#active-view-rooms button[name=roomListPrev]").removeAttr("disabled"))};
popup.prototype.rooms.prototype.retrieve=function(){var a=this;$("#roomTableHtml").html("");fimApi.getRooms(this.options,{each:function(b){$("#roomTableHtml").append(a.entryTemplate(fim_getHandlebarsPhrases(b)))},end:function(a,c){0==Object.keys(a).length?($("#active-view-rooms button[name=roomListNext]").attr("disabled",!0),$("#roomTableHtml").html(Handlebars.compile($("#view-rooms-emptyResultSet").html())(fim_getHandlebarsPhrases()))):($("#active-view-rooms button[name=roomListNext]").removeAttr("disabled"),
$("#active-view-rooms button[name=roomListNext]").unbind("click").bind("click",function(){fim_setHashParameter("page",Number(c.nextPage))}))}})};popup.prototype.rooms.prototype.update=function(a,b){this.options[a]=b};var standard=function(){this.userId=0;this.anonId=this.sessionHash="";this.activeLogin={};this.lastEvent=0;this.notifications={}};
standard.prototype.initialLogin=function(a){var b=this,c=a.finish;a.finish=function(d){c&&c(d);b.anonId||($.cookie("webpro_username",a.username,{expires:14}),$.cookie("webpro_password",a.password,{expires:14}),fimApi.getUnreadMessages(null,{each:function(a){b.missedMessageHandler(a)}}));window.roomId||(window.roomId=d.userData.defaultRoomId?d.userData.defaultRoomId:1);fim_renderHandlebarsInPlace($("#entry-template"));fim_hashParse()};this.login(a)};
standard.prototype.setUserData=function(a){var b=a.messageFormatting.split(";");a.messageFormattingObj={};jQuery.each(b,function(b,d){b=d.split(":");a.messageFormattingObj[b[0]]=b[1]});this.activeLogin.userData=window.activeLogin.userData=a;this.userId=window.userId=a.id;this.anonId=window.anonId=a.anonId};standard.prototype.setActiveLogin=function(a){this.activeLogin=window.activeLogin=a;this.setUserData(a.userData)};
standard.prototype.login=function(a){var b=this;a.start&&a.start();fimApi.login({grant_type:a.grantType,username:a.username,password:a.password,access_token:a.sessionHash,refresh_token:a.refreshToken,client_id:"WebPro"},{end:function(c){"userData"in c?b.setActiveLogin(c):b.activeLogin||(dia.error("The login did not return proper information. The page will reload in 3 seconds..."),setTimeout(function(){location.reload()},3E3));b.sessionHash=window.sessionHash=c.access_token;fim_removeHashParameter("sessionHash");
a.finish&&a.finish(c);c.expires&&c.refresh_token&&($.cookie("webpro_refreshToken",c.refresh_token),setTimeout(function(){b.login({grantType:"refresh_token",refreshToken:c.refresh_token})},1E3*c.expires/2));fimApi.getRooms({roomIds:window.serverSettings.officialRooms.concat(b.activeLogin.userData.favRooms).concat(b.activeLogin.userData.watchRooms)},{begin:function(){$("#navbar div[name=favRoomsList]").html("");$("#navbar div[name=officialRoomsList]").html("");$("#navbar div[name=watchRoomsList]").html("")},
each:function(a){var c=$("<a>").attr({href:"#room="+a.id,"class":"dropdown-item"}).text(a.name);-1!=b.activeLogin.userData.favRooms.indexOf(a.id)&&$("#navbar div[name=favRoomsList]").append(c.clone());-1!=b.activeLogin.userData.watchRooms.indexOf(a.id)&&$("#navbar div[name=watchRoomsList]").append(c.clone());a.official&&$("#navbar div[name=officialRoomsList]").append(c.clone())}});$("#privateRoomForm input[name=userName]").autocompleteHelper("users");$("#privateRoomForm").submit(function(){var a=
$("#privateRoomForm input[name=userName]").val(),c=$("#privateRoomForm input[name=userName]").attr("data-id"),f=function(a){window.location.hash="#room=p"+[b.userId,a].join()};!c&&a?f(c):a?$.when(Resolver.resolveUsersFromNames([a]).then(function(b){f(b[a].id)})):dia.error("Please enter a username.");return!1});b.getEvents();return!1},error:function(b){a.error&&a.error(b);return!1}})};
standard.prototype.getEventsFromFallback=function(){var a=this;fimApi.getEventsFallback({streamType:"user",lastEvent:this.lastEvent},{each:function(b){a.lastEvent=Math.max(Number(b.id),Number(a.lastEvent));"missedMessage"==b.eventName&&a.missedMessageHandler(b.data)},end:function(){window.requestSettings.serverSentEvents?a.getEventsFromStream():window.setTimeout(function(){a.getEventsFromFallback()},3E3)}})};
standard.prototype.getEventsFromStream=function(){var a=this;(new EventSource(directory+"stream.php?streamType=user&lastEvent="+this.lastEvent+"&access_token="+this.sessionHash)).addEventListener("missedMessage",function(b){return function(c){a.lastEvent=Math.max(a.lastEvent,c.id);b.call(a,JSON.parse(c.data))}}(this.missedMessageHandler),!1)};standard.prototype.getEvents=function(){window.requestSettings.serverSentEvents?this.getEventsFromStream():this.getEventsFromFallback()};
standard.prototype.missedMessageHandler=function(a){a.roomId!=window.roomId&&(console.log("missed message",a),this.notifications["room"+a.roomId]||(this.notifications["room"+a.roomId]=$.notify({url:"#room="+a.roomId,message:$("<span>").attr({"class":"missedMessage",id:"missedMessage"+a.roomId,"data-roomId":a.roomId}).prop("outerHTML")},{newest_on_top:!0,type:"info",placement:{from:"top",align:"right"},delay:0,animate:{exit:""},onClose:function(){fimApi.markMessageRead(a.roomId)},url_target:"_self"})),
$("#missedMessage"+a.roomId.toString().replace(",","\\,")).replaceWith($("<span>").text("New message from ").append(fim_buildUsernameTag($("<strong>"),a.senderId)).append(" has been made in ").append(fim_buildRoomNameTag($("<strong>"),a.roomId)).append(a.missedMessages?$("<span>").text("(Other messages: "+a.otherMessages+")"):"")))};
standard.prototype.logout=function(){$.cookie("webpro_username",null);$.cookie("webpro_password",null);$.cookie("webpro_refreshToken",null);fimApi.getMessages(null,{close:!0});fimApi.getActiveUsers(null,{close:!0});fimApi.getUnreadMessages(null,{close:!0});$("#logout").parent().show();$("#login").parent().hide();window.popup.login()};var fimApi=function(a){var b=this;this.directory=a;this.lastSessionHash="";this.requestDefaults={close:!1,timerId:1,refresh:!1,timeout:5E3,cache:!1,begin:function(){},error:function(){},exception:function(){},each:function(){},reverseEach:!1,end:function(){},async:!0,action:null};this.timers={};this.done=function(a,b){return function(c){try{var d=c[b?b:Object.keys(c)[0]];a.begin(d);a.reverseEach&&(d=d.reverse());$.each(d,function(b,c){a.each(c)});a.end(d,c.metadata)}catch(g){console.log("Failed to parse information: ",
c,g)}}};this.fail=function(a,b){return function(b){!("responseJSON"in b)&&"responseText"in b&&"{"===b.responseText.slice(0,1)&&(b.responseJSON=JSON.parse(b.responseText));if(!("responseJSON"in b))console.log("Unable to parse failure response.");else if("exception"in b.responseJSON&&(console.log("Server Exception",JSON.stringify(b.responseJSON)),"The access token provided has expired"!=b.responseJSON.exception.details))return a.exception(b.responseJSON.exception);return a.error(b)}};this.timer=function(a,
d,e){a.close?(console.log("close "+d+"_"+a.timerId,b.timers),clearInterval(b.timers[d+"_"+a.timerId]),delete b.timers[d+"_"+a.timerId]):(e(a),0<a.refresh&&(clearInterval(b.timers[d+"_"+a.timerId]),b.timers[d+"_"+a.timerId]=setInterval(function(){e(a)},a.refresh)))};this.registerDefaultExceptionHandler=function(a){this.requestDefaults.exception=a};this.getDefaultExceptionHandler=function(){return this.requestDefaults.exception};this.mergeDefaults=function(a,b){var c={},d;for(d in a){if(!(d in b))throw"Invalid data in object call: "+
d;null!==a[d]&&void 0!==a[d]&&(c[d]=a[d])}for(d in b)d in c||null===b[d]||(c[d]=b[d]);return c};this.jsonify=function(a,b){a=void 0===a?{}:Object.create(a);for(var c in b)b[c]in a&&(a[b[c]]=JSON.stringify(a[b[c]]));return a}};
fimApi.prototype.login=function(a,b){var c=this;a=this.mergeDefaults(a,{grant_type:"password",username:null,password:null,access_token:null,refresh_token:null,client_id:""});b=this.mergeDefaults(b,this.requestDefaults);return $.ajax({url:this.directory+"validate.php",type:"POST",data:a,timeout:b.timeout,cache:b.cache}).done(function(a){a.login.access_token&&(c.lastSessionHash=a.login.access_token);b.end(a.login)}).fail(function(a){b.error(a.responseJSON.exception)})};
fimApi.prototype.getUsers=function(a,b){var c=this;a=this.mergeDefaults(a,{info:["self","groups","profile"],access_token:this.lastSessionHash,id:null,userIds:null,userNames:null,userNameSearch:null});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/user.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getUsers(a,b)}))};
fimApi.prototype.createUser=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);return $.ajax({type:"post",url:this.directory+"api/user.php",data:this.mergeDefaults(a,{name:null,password:null,birthDate:null,email:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getUsers(a,b)}))};
fimApi.prototype.getRooms=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,id:null,roomIds:null,roomNames:null,roomNameSearch:null,permFilter:null,page:null});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/room.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getRooms(a,b)}))};
fimApi.prototype.getEventsFallback=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);this.timer(b,"getEventsFallback",function(b){$.ajax({type:"get",url:c.directory+"stream.php",data:c.mergeDefaults(a,{fallback:!0,access_token:c.lastSessionHash,streamType:null,queryId:null,lastEvent:null,lastMessage:null}),timeout:b.timeout,cache:b.cache}).done(function(a){c.done(b)(a)}).fail(function(d){b.refresh&&c.getEventsFallback(null,{close:!0});c.fail(b,function(){c.getEventsFallback(a,
b)})(d)})})};fimApi.prototype.getMessages=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);this.timer(b,"getMessages",function(b){$.ajax({type:"get",url:c.directory+"api/message.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash,roomId:null,id:null,userIds:null,messageIdEnd:null,messageIdStart:null,page:null,messageTextSearch:null}),timeout:b.timeout,cache:b.cache}).done(c.done(b)).fail(c.fail(b,function(){c.getMessages(a,b)}))})};
fimApi.prototype.sendMessage=function(a,b,c){var d=this;b=this.mergeDefaults(b,{access_token:this.lastSessionHash,ignoreBlock:!1,message:null,flag:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({roomId:a}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.sendMessage(a,b,c)}))};
fimApi.prototype.editMessage=function(a,b,c,d){var e=this;c=this.mergeDefaults(c,{ignoreBlock:!1,message:null,flag:null});d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({_action:"edit",access_token:this.lastSessionHash,id:b,roomId:a}),type:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.editMessage(a,b,c,d)}))};
fimApi.prototype.deleteMessage=function(a,b,c){var d=this;c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/message.php?"+$.param({_action:"delete",access_token:this.lastSessionHash,id:b,roomId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.deleteMessage(a,b,c)}))};
fimApi.prototype.getUnreadMessages=function(a,b){var c=this;b=this.mergeDefaults(b,this.mergeDefaults({timeout:3E4,refresh:3E4},this.requestDefaults));fimApi.timer(b,"getUnreadMessages",function(b){$.ajax({type:"get",url:c.directory+"api/unreadMessages.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash}),timeout:b.timeout,cache:b.cache}).done(c.done(b)).fail(function(d){b.refresh&&c.getUnreadMessages(null,{close:!0});c.fail(b,function(){c.getUnreadMessages(a,b)})(d)})})};
fimApi.prototype.getFiles=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,userIds:[],fileIds:[],page:0});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/file.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getFiles(a.requestSettings)}))};
fimApi.prototype.getStats=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/stats.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,number:10}),timeout:b.timeout,cache:b.cache}).done(this.done(b,"roomStats")).fail(this.fail(b,function(){c.getStats(a,b)}))};
fimApi.prototype.getKicks=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/kick.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,userId:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getKicks(a,b)}))};
fimApi.prototype.getCensorLists=function(a,b){var c=this;a=this.mergeDefaults(a,{access_token:this.lastSessionHash,roomId:null,listIds:null,includeWords:1});b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/getCensorLists.php",data:a,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getCensorLists(a,b)}))};
fimApi.prototype.getActiveUsers=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);fimApi.timer(b,"getActiveUsers",function(b){$.ajax({type:"get",url:c.directory+"api/userStatus.php",data:c.mergeDefaults(a,{access_token:c.lastSessionHash,roomIds:null,userIds:null,onlineThreshold:null}),timeout:b.timeout,cache:b.cache}).done(c.done(b,"users")).fail(function(d){b.refresh&&c.getActiveUsers(null,{close:!0});c.fail(b,function(){c.getActiveUsers(a,b)})(d)})})};
fimApi.prototype.getGroups=function(a,b){var c=this;b=this.mergeDefaults(b,this.requestDefaults);$.ajax({type:"get",url:this.directory+"api/group.php",data:this.mergeDefaults(a,{access_token:this.lastSessionHash,groupIds:null,groupNames:null,groupNameSearch:null}),timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.getGroups(a,b)}))};
fimApi.prototype.acHelper=function(a){var b=this;return function(c,d){$.ajax({type:"get",url:b.directory+"api/acHelper.php",data:{access_token:b.lastSessionHash,list:a,search:c.term},success:function(a){d($.map(a.entries,function(a,b){return{label:a,value:b}}))}})}};
fimApi.prototype.kickUser=function(a,b,c,d){var e=this;d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/kick.php?"+$.param({access_token:this.lastSessionHash,roomId:b,userId:a}),type:"POST",data:{length:c},timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.kickUser(a,b,c,d)}))};
fimApi.prototype.unkickUser=function(a,b,c){var d=this;c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/kick.php?"+$.param({access_token:this.lastSessionHash,_action:"delete",roomId:b,userId:a}),type:"POST",timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.unkickUser(a,b,c)}))};
fimApi.prototype.markMessageRead=function(a,b){var c=this,d={access_token:this.lastSessionHash,_action:"delete",roomId:a};b=this.mergeDefaults(b,this.requestDefaults);$.ajax({url:this.directory+"api/unreadMessages.php",data:d,timeout:b.timeout,cache:b.cache}).done(this.done(b)).fail(this.fail(b,function(){c.markMessageRead(a,b)}))};
fimApi.prototype.editUserOptions=function(a,b,c){var d=this;b=this.mergeDefaults(b,{defaultFormatting:null,defaultColor:null,defaultHighlight:null,defaultRoomId:null,watchRooms:null,favRooms:null,ignoreList:null,friendsList:null,profile:null,defaultFontface:null,parentalAge:null,parentalFlags:null,avatar:null,privacyLevel:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/userOptions.php?"+$.param({access_token:this.lastSessionHash,_action:a?a:"edit"}),type:"POST",
data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.editUserOptions(a,b,c)}))};fimApi.prototype.favRoom=function(a){this.editUserOptions("create",{favRooms:[a]})};fimApi.prototype.unfavRoom=function(a){this.editUserOptions("delete",{favRooms:[a]})};fimApi.prototype.watchRoom=function(a){this.editUserOptions("create",{watchRooms:[a]})};fimApi.prototype.unwatchRoom=function(a){this.editUserOptions("delete",{watchRooms:[a]})};
fimApi.prototype.editRoom=function(a,b,c,d){var e=this;c=this.mergeDefaults(c,{access_token:this.lastSessionHash,name:null,defaultPermissions:null,userPermissions:null,groupPermissions:null,censorLists:null,parentalAge:null,parentalFlags:null,hidden:null,official:null});d=this.mergeDefaults(d,this.requestDefaults);$.ajax({url:this.directory+"api/room.php?"+$.param(this.mergeDefaults({},{id:a,_action:b})),method:"POST",data:c,timeout:d.timeout,cache:d.cache}).done(this.done(d)).fail(this.fail(d,function(){e.editRoom(a,
c,d)}))};fimApi.prototype.createRoom=function(a,b){this.editRoom(null,"create",a,b)};fimApi.prototype.deleteRoom=function(a,b){this.editRoom(a,"delete",{},b)};fimApi.prototype.undeleteRoom=function(a,b){this.editRoom(a,"undelete",{},b)};
fimApi.prototype.editRoomPermission=function(a,b,c,d,e,f){var g=this,h={_action:a,access_token:this.lastSessionHash,roomId:c};h[b+"Id"]=d;f=this.mergeDefaults(f,this.requestDefaults);$.ajax({url:this.directory+"api/roomPermission.php?"+$.param(h),method:"POST",data:{permissions:e},timeout:f.timeout,cache:f.cache}).done(this.done(f)).fail(this.fail(f,function(){g.editRoomPermission(a,b,c,d,e,f)}))};
fimApi.prototype.editRoomPermissionUser=function(a,b,c,d){this.editRoomPermission("edit","user",a,b,c,d)};fimApi.prototype.editRoomPermissionGroup=function(a,b,c,d){this.editRoomPermission("edit","group",a,b,c,d)};fimApi.prototype.deleteRoomPermissionUser=function(a,b,c,d){this.deleteRoomPermission("delete","user",a,b,c,d)};fimApi.prototype.deleteRoomPermissionGroup=function(a,b,c,d){this.deleteRoomPermission("delete","group",a,b,c,d)};
fimApi.prototype.createRoomPermissionUser=function(a,b,c,d){this.createRoomPermission("create","user",a,b,c,d)};fimApi.prototype.createRoomPermissionGroup=function(a,b,c,d){this.createRoomPermission("create","group",a,b,c,d)};
fimApi.prototype.editUserStatus=function(a,b,c){var d=this;b=this.mergeDefaults(b,{status:null,typing:null});c=this.mergeDefaults(c,this.requestDefaults);$.ajax({url:this.directory+"api/userStatus.php?"+$.param({_action:"edit",access_token:this.lastSessionHash,roomIds:[a]}),type:"POST",data:b,timeout:c.timeout,cache:c.cache}).done(this.done(c)).fail(this.fail(c,function(){d.editUserStatus(a,b,c)}))};fimApi.prototype.ping=function(a,b){this.editUserStatus(a,{status:""},b)};
fimApi.prototype.exitRoom=function(a,b){this.editUserStatus(a,{status:"offline"},b)};fimApi.prototype.startedTyping=function(a,b){this.editUserStatus(a,{typing:!0},b)};fimApi.prototype.stoppedTyping=function(a,b){this.editUserStatus(a,{typing:!1},b)};fimApi.prototype.changeAvatar=function(a,b){this.editUserOptions({avatarHash:a},b)};/*
 Joseph T. Parsons 2017
*/
var autoEntry=function(a,b){var c=this;this.options=b;if(!this.options.name)throw Error("No name provided.");this.autocompleteInput=$("<input>").attr({type:"text",name:this.options.name+"Bridge",id:this.options.name+"Bridge","class":"ui-autocomplete-input form-control",autocomplete:"off"});this.autocompleteSubmit=$("<button>").attr({"class":"btn btn-success"}).text("Add");this.autocompleteForm=$("<form>").attr("class","input-group").append($("<span>").attr("class","input-group-prepend").append(this.autocompleteSubmit),
this.autocompleteInput);this.autocompleteInput.autocompleteHelper(this.options.list);this.autocompleteForm.submit(function(a){c.autocompleteInput.attr("data-id")?(c.addEntry(c.autocompleteInput.attr("data-id"),c.autocompleteInput.attr("data-value")),c.autocompleteInput.val("")):($("button",a.target).popover({placement:"bottom",content:"Invalid Entry",trigger:"manual"}).popover("show"),setTimeout(function(){$("button",a.target).popover("dispose")},1E3));return!1});a.append(this.autocompleteForm);this.autocompleteValue=
$('<input type="hidden" name="'+this.options.name+'" id="'+this.options.name+'">');this.autocompleteValue.insertAfter(a);this.autocompleteDiv=$('<div class="d-flex flex-wrap">').attr("id",this.options.name+"List");this.autocompleteDiv.insertAfter(a);"default"in b&&this.displayEntries(b["default"]);return this};
autoEntry.prototype={setOnAdd:function(a){this.options.onAdd=a},addEntry:function(a,b,c){var d=this;void 0===c&&(c=!1);var e=!0;!a&&b?e=$.when(this.options.resolveFromNames([b])).then(function(c){a=c[b].id}):!b&&a&&(e=$.when(this.options.resolveFromIds([a]).then(function(c){b=c[a].name})));$.when(e).then(function(){if(a)if($("#"+d.options.name+"SubList"+a).length)d.autocompleteSubmit.popover({placement:"bottom",content:"Duplicate Entry",trigger:"manual"}).popover("show"),setTimeout(function(){this.autocompleteSubmit.popover("dispose")},
1E3),d.autocompleteInput.val("");else{var e=fim_getUsernameDeferred(a),g=$('<span class="input-group-text">');"users"===d.options.list?g=fim_buildUsernameTag(g,a,e,!1,!1,!0):g.text(b);var h=!1;"users"===d.options.list&&(h=fim_buildUsernameTag($('<span class="input-group-text">'),a,e,!1,!0,!1));d.autocompleteValue.val(d.autocompleteValue.val()+","+a);d.autocompleteDiv.append($("<div>").attr({id:d.options.name+"SubList"+a,"class":"input-group input-group-sm m-1",style:"width: auto; white-space: nowrap"}).append($("<span>").attr({"class":"input-group-prepend",
style:"display: inline-block; vertical-align: top"}).append($("<button>").attr({type:"button","class":"btn btn-danger"}).text("\u00d7").click(function(){d.removeEntry(a)})),$("<span>").attr({"class":"input-group-append"}).append(g),h?$("<span>").attr({"class":"input-group-append input-group-addon-img"}).append(h):""));if(!c&&d.options.onAdd)d.options.onAdd(a)}else dia.error("Invalid entry.")})},removeEntry:function(a){var b=this.options;this.autocompleteValue.val(this.autocompleteValue.val().replace(new RegExp("(^|,)"+
a+"(,|$)"),"$1$2").replace(/^,|(,),|,$/,"$1"));$("#"+this.options.name+"SubList"+a).fadeOut(500,function(){$(this).remove();if("function"===typeof b.onRemove)b.onRemove(a)})},displayEntries:function(a){var b=this;var c="object"===typeof a?a:"string"===typeof a&&0<a.length?a.split(","):[];$.when(this.options.resolveFromIds(c)).then(function(a){for(var d=0;d<c.length;d++)a[c[d]]&&b.addEntry(c[d],a[c[d]].name,!0)})},getList:function(){return this.autocompleteValue.val().split(",").filter(Number)}};var Debounce=function(){function a(){}a.prototype.invoke=function(a,c,d){var b=this,f=arguments,g=d&&!this.timeout;clearTimeout(this.timeout);this.timeout=setTimeout(function(){this.timeout=null;d||a.apply(b,f)},c);g&&a.apply(b,f)};return a}();var Resolver=function(){function a(){}a.cacheEntry=function(b,c){-1===a["cached"+b+"Ids"].indexOf(c.id)&&(a["cached"+b+"Ids"].push(String(c.id)),a["cached"+b+"Names"].push(String(c.name)),a["cached"+b+"Properties"].push(c))};a.getCapital=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};a.getPlural=function(b){return a.getCapital(b)+"s"};a.resolve=function(b,c,d){var e=$.Deferred(),f={},g=[],h=[],k=a.getPlural(c),l=b+k;if("id"==c)for(k=0;k<d.length;k++)d[k]=String(d[k]);k=function(d){if("id"===
c||"name"===c)d=String(d);if(-1!==a["cached"+l].indexOf(d))f[d]=a["cached"+b+"Properties"][a["cached"+l].indexOf(d)];else if(-1!==a["waiting"+l].indexOf(d)){var e=setInterval(function(){console.log(["resolveWaitRetry",l,d,a["cached"+l]]);-1!==a["cached"+l].indexOf(d)?(clearInterval(e),f[d]=a["cached"+b+"Properties"][a["cached"+l].indexOf(d)],h.splice($.inArray(d,h),1)):-1===a["waiting"+l].indexOf(d)&&(clearInterval(e),h.splice($.inArray(d,h),1))},100);h.push(d)}else a["waiting"+l].push(d),g.push(d)};
for(var m=0;m<d.length;m++)k(d[m]);0<g.length&&(d={},d[l]=g,fimApi["get"+a.getPlural(b)](d,{each:function(d){a.cacheEntry(b,d);f[d[c]]=d},end:function(){jQuery.each(g,function(b,c){a["waiting"+l].splice($.inArray(c,a["waiting"+l]),1)});g=[]}}));if(0<h.length||0<g.length)var n=setInterval(function(){0==h.length&&0==g.length&&(clearInterval(n),e.resolve(f))},100);else e.resolve(f);return e.promise()};a.resolveUsersFromIds=function(b){return a.resolve("user","id",b)};a.resolveUsersFromNames=function(b){return a.resolve("user",
"name",b)};a.resolveRoomsFromIds=function(b){return a.resolve("room","id",b)};a.resolveRoomsFromNames=function(b){return a.resolve("room","name",b)};a.resolveGroupsFromIds=function(b){return a.resolve("group","id",b)};a.resolveGroupsFromNames=function(b){return a.resolve("group","name",b)};a.resolveFromId=function(b,c){return a["resolve"+a.getCapital(b)+"FromIds"]([c])};a.resolveFromName=function(b,c){return a["resolve"+a.getCapital(b)+"FromNames"]([c])};a.cacheduserIds=[];a.cacheduserNames=[];a.cacheduserProperties=
[];a.waitinguserIds=[];a.waitinguserNames=[];a.waitinguserProperties=[];a.cachedroomIds=[];a.cachedroomNames=[];a.cachedroomProperties=[];a.waitingroomIds=[];a.waitingroomNames=[];a.waitingroomProperties=[];a.cachedgroupIds=[];a.cachedgroupNames=[];a.cachedgroupProperties=[];a.waitinggroupIds=[];a.waitinggroupNames=[];a.waitinggroupProperties=[];return a}();popup.prototype.settings={init:function(){var a=[];a=[];new autoEntry($("#changeSettingsForm [name=ignoreListContainer]"),{name:"ignoreList","default":window.activeLogin.userData.ignoredUsers,list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});new autoEntry($("#changeSettingsForm [name=friendsListContainer]"),{name:"friendsList","default":window.activeLogin.userData.friendedUsers,list:"users",resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames});
new autoEntry($("#changeSettingsForm [name=watchRoomsContainer]"),{name:"watchRooms","default":window.activeLogin.userData.watchRooms,list:"rooms",resolveFromIds:Resolver.resolveRoomsFromIds,resolveFromNames:Resolver.resolveRoomsFromNames});$("#changeSettingsForm input[name=defaultRoom]").autocompleteHelper("rooms",window.activeLogin.userData.defaultRoomId);a=[0,0,0];"color"in window.activeLogin.userData.messageFormattingObj&&($("#defaultColour").css("background-color",window.activeLogin.userData.messageFormattingObj.color),
a=window.activeLogin.userData.messageFormattingObj.color.slice(4,-1).split(","));$("#defaultColour").ColorPicker({color:{r:a[0],g:a[1],b:a[2]},onChange:function(a,c,d){$("#defaultColour").css("background-color","rgb("+d.r+","+d.g+","+d.b+")");$("#fontPreview").css("color","rgb("+d.r+","+d.g+","+d.b+")")}});a=[255,255,255];"background-color"in window.activeLogin.userData.messageFormattingObj&&($("#defaultHighlight").css("background-color",window.activeLogin.userData.messageFormattingObj["background-color"]),
a=window.activeLogin.userData.messageFormattingObj["background-color"].slice(4,-1).split(","));$("#defaultHighlight").ColorPicker({color:a?{r:a[0],g:a[1],b:a[2]}:!1,onChange:function(a,c,d){$("#defaultHighlight, #fontPreview").css("background-color","rgb("+d.r+","+d.g+","+d.b+")")}});$('input[name=privacyLevel][value="'+window.activeLogin.userData.privacyLevel+'"]').prop("checked",!0);window.snd.volume&&$("#audioVolume").attr("value",100*snd.volume);$("input[name=showAvatars], input[name=reversePostOrder], input[name=disableFormatting], input[name=disableVideos], input[name=disableImages], input[name=audioDing], input[name=webkitNotifications], input[name=hideTimes], input[name=alternateSelfPosts]").change(function(){var a=
$(this).attr("name");$(this).is(":checked")&&!window.settings[a]?(window.settings[a]=!0,$.cookie("webpro_settings",$.cookie("webpro_settings").toNumber()|window.settingNames[a],{expires:14})):!$(this).is(":checked")&&window.settings[a]&&(window.settings[a]=!1,$.cookie("webpro_settings",$.cookie("webpro_settings").toNumber()&~window.settingNames[a],{expires:14}))});$("#changeSettingsForm").submit(function(){var a=[];$("#defaultBold").is(":checked")&&a.push("bold");$("#defaultItalics").is(":checked")&&
a.push("italic");fimApi.editUserOptions("edit",{defaultFontface:$("#defaultFace option:selected").val(),defaultFormatting:$('form#changeSettingsForm input[name="defaultFormatting[]"]:checked').map(function(){return $(this).attr("value")}).get(),defaultHighlight:"rgba(0, 0, 0, 0)"===$("#fontPreview").css("background-color")?null:$("#fontPreview").css("background-color").slice(4,-1),defaultColor:$("#fontPreview").css("color").slice(4,-1),defaultRoomId:$("#changeSettingsForm input[name=defaultRoom]").attr("data-id"),
watchRooms:$("#changeSettingsForm input[name=watchRooms]").val().split(","),ignoreList:$("#changeSettingsForm input[name=ignoreList]").val().split(","),friendsList:$("#changeSettingsForm input[name=friendsList]").val().split(","),profile:$("#changeSettingsForm input[name=profile]").val(),parentalAge:$("form#changeSettingsForm select[name=parentalAge] option:selected").val(),parentalFlags:$("form#changeSettingsForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),
privacyLevel:$("input[name=privacyLevel]:radio:checked").val()},{each:function(a){console.log(a)},end:function(a){var b=[];jQuery.each(a,function(a,c){b.push("<li>"+a+": "+c.details+"</li>")});b.length?dia.error("Some of your settings have been updated. However, the following values were unable to be processed:<br /><ul>"+b.join("")+"</ul>"):(dia.info("Your settings have been updated successfully."),window.location.hash="#",fimApi.getUsers({id:window.activeLogin.userData.id},{each:function(a){window.standard.setUserData(a)}}))}});
return!1})}};popup.prototype.editRoom={options:{roomId:null},setRoomId:function(a){this.options.roomId=a?a:null},init:function(){},retrieve:function(){var a=this;var b=null!=this.options.roomId?"edit":"create";var c=new autoEntry($("#moderatorsContainer"),{name:"moderators",list:"users",onAdd:function(c){"edit"===b&&fimApi.createRoomPermissionUser(a.options.roomId,c,["view","post","moderate","properties","grant"])},onRemove:function(c){"edit"===b&&fimApi.deleteRoomPermissionUser(a.options.roomId,c,["moderate",
"properties","grant"])},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames}),d=new autoEntry($("#allowedUsersContainer"),{name:"allowedUsers",list:"users",onAdd:function(c){"edit"===b&&fimApi.createRoomPermissionUser(a.options.roomId,c,["view","post"])},onRemove:function(c){"edit"===b&&fimApi.deleteRoomPermissionUser(a.options.roomId,c,"view post changeTopic moderate properties grant".split(" "))},resolveFromIds:Resolver.resolveUsersFromIds,resolveFromNames:Resolver.resolveUsersFromNames}),
e=new autoEntry($("#allowedGroupsContainer"),{name:"allowedGroups",list:"groups",onAdd:function(c){"edit"===b&&fimApi.createRoomPermissionGroup(a.options.roomId,c,["view","post"])},onRemove:function(c){"edit"===b&&fimApi.deleteRoomPermissionGroup(a.options.roomId,c,"view post changeTopic moderate properties grant".split(" "))},resolveFromIds:Resolver.resolveGroupsFromIds,resolveFromNames:Resolver.resolveGroupsFromNames});fimApi.getCensorLists({roomId:this.options.roomId,includeWords:0},{each:function(a){if(a.status)var b=
a.status;else if("white"===a.listType)b="block";else if("black"===a.listType)b="unblock";else throw"Bad logic.";$("#editRoomForm [name=censorLists]").append($("<label>").attr("class","btn btn-secondary m-1").text(a.listName).prepend($("<input>").attr({type:"checkbox",name:"censorLists",value:a.listId}).attr(a.listOptions&2?{disabled:"disabled"}:{}).attr("block"==b?{checked:"checked"}:{})))}});null!=this.options.roomId&&fimApi.getRooms({id:this.options.roomId},{each:function(a){var b=[],f=[];jQuery.each(a.userPermissions,
function(a,c){c.moderate&&c.properties&&c.grant?f.push(a):c.post&&b.push(a)});d.displayEntries(b);c.displayEntries(f);var k=[];jQuery.each(a.groupPermissions,function(a,b){b.post&&k.push(a)});e.displayEntries(k);"view"in a.defaultPermissions&&$("#editRoomForm input[name=allowViewing]").prop("checked",!0);"post"in a.defaultPermissions&&$("#editRoomForm input[name=allowPosting]").prop("checked",!0);$("#editRoomForm input[name=name]").val(a.name);$("#editRoomForm input[name=official]").prop("checked",
a.official);$("#editRoomForm input[name=hidden]").prop("checked",a.hidden);jQuery.each(a.parentalFlags,function(a,b){$("#editRoomForm input[name=parentalFlags][value="+b+"]").prop("checked",!0)});$("#editRoomForm select[name=parentalAge] option[value="+a.parentalAge+"]").attr("selected","selected")}});$("#editRoomForm").submit(function(){var f=[];$("#editRoomForm input[name=allowViewing]").is(":checked")&&f.push("view");$("#editRoomForm input[name=allowPosting]").is(":checked")&&f.push("post");var g=
{};jQuery.each($("#editRoomForm input[name=censorLists]:checked").map(function(){return $(this).attr("value")}).get(),function(a,b){g[b]=1});jQuery.each($("#editRoomForm input[name=censorLists]:not(:checked)").map(function(){return $(this).attr("value")}).get(),function(a,b){g[b]=0});fimApi.editRoom(a.options.roomId,b,{name:$("#editRoomForm input[name=name]").val(),defaultPermissions:f,parentalAge:$("#editRoomForm select[name=parentalAge] option:selected").val(),parentalFlags:$("#editRoomForm input[name=parentalFlags]:checked").map(function(){return $(this).attr("value")}).get(),
censorLists:g,official:$("#editRoomForm input[name=official]").is(":checked"),hidden:$("#editRoomForm input[name=hidden]").is(":checked")},{end:function(a){var f=this;"create"===b&&(d.getList().forEach(function(a){fimApi.createRoomPermissionUser(f.options.roomId,a,["view","post"])}),c.getList().forEach(function(a){fimApi.createRoomPermissionUser(f.options.roomId,a,"view post changeTopic moderate properties grant".split(" "))}),e.getList().forEach(function(a){fimApi.createRoomPermissionGroup(f.options.roomId,
a,["view","post"])}));window.location.hash="#";dia.full({content:$l("editRoom.finish."+b+"Title")+'<br /><br /><form action="#room='+a.id+'"><div class="input-group"><input autofocus type="text" value="'+window.currentLocation+"#room="+a.id+'" name="url" class="form-control"  /><span class="input-group-btn"><button class="btn btn-primary">Go!</button></span></div></form>',title:$l("editRoom.finish."+b+"Message"),buttons:{Open:function(){window.location.hash="#room="+a.id},Okay:function(){}}})}});
return!1});return!1}};popup.prototype.kicks=function(){this.options={userId:null,roomId:null};this.entryTemplate=Handlebars.compile($("#view-kicks-row").html())};popup.prototype.kicks.prototype.init=function(a){console.log("init",a);a.room&&"0"!=a.room||window.activeLogin.userData.permissions.modRooms||this.setUser(window.userId)};
popup.prototype.kicks.prototype.retrieve=function(){var a=this;jQuery.each(["user","room"],function(b,c){$("#active-view-kicks form#kicksSearch input[name="+c+"]").autocompleteHelper(c+"s",a.options[c+"Id"]).off("autocompleteChange").on("autocompleteChange",function(){console.log("change event");fim_setHashParameter(c,$(this).attr("data-id"))})});$("#active-view-kicks table > tbody").html("");fimApi.getKicks(this.options,{each:function(b){var c=$("<span>"),d=fim_buildUsernameTagPromise(c,b.userId,
fim_getUsernameDeferred(b.userId));jQuery.each(b.kicks,function(e,f){var g=$("<span>");e=fim_buildUsernameTagPromise(g,f.kickerId,fim_getUsernameDeferred(f.kickerId));var h=$("<span>"),k=fim_buildRoomNameTagPromise(h,f.roomId,fim_getRoomNameDeferred(f.roomId));$.when(d,e,k).then(function(){$("#kickedUsers").append(a.entryTemplate(fim_getHandlebarsPhrases({kick:Object.assign({},b,f),userTag:c,kickerTag:g,roomTag:h})))})})}})};
popup.prototype.kicks.prototype.setRoom=function(a){a&&0!=a?this.options.roomId!==a&&(this.options.roomId=a):this.options.roomId=null};popup.prototype.kicks.prototype.setUser=function(a){a&&0!=a?this.options.roomId!==a&&(this.options.userId=a):this.options.userId=null};popup.prototype.room=function(){this.options={roomId:0,lastEvent:0,lastMessage:0};this.windowBlurred=this.faviconFlashTimer=this.roomData=!1;this.messageIndex=[];this.visibilitychangeListener=this.blurListener=this.focusListener=this.pingInterval=this.eventTimeout=this.roomSource=this.isTyping=!1;this.debounce=new Debounce};
popup.prototype.room.prototype.insertDoc=function(){$("#modal-insertDoc").modal();$("#uploadFileForm [type=submit]").attr("disabled","disabled");"fileUploads"in window.serverSettings?"function"!==typeof FileReader?$("#uploadFileForm").html($l("uploadErrors.notSupported")):($("#uploadFileForm").unbind("submit").bind("submit",function(){var a=$('input#fileUpload[type="file"]').prop("files");0==a.length?dia.error("Please select a file to upload."):($("#chatContainer").fileupload("add",{files:a,formData:{fileName:a[0].name}}),
$("#modal-insertDoc").modal("hide"));return!1}),$("#fileUpload").unbind("change").bind("change",function(){var a=new FileReader;$("#imageUploadSubmitButton").attr("disabled","disabled").button({disabled:!0});if(0===this.files.length)dia.error("No files selected!");else if(1<this.files.length)dia.error("Too many files selected!");else{console.log("FileReader started.");var b=this.files[0].size,c=this.files[0].name.split("."),d=c[c.length-1].toLowerCase();d in window.serverSettings.fileUploads.extensionChanges&&
(d=window.serverSettings.fileUploads.extensionChanges[d]);-1===$.inArray(d,$.toArray(window.serverSettings.fileUploads.allowedExtensions))?$("#uploadFileFormPreview").html($l("uploadErrors.badExtPersonal")):b>window.serverSettings.fileUploads.sizeLimits[d]?$("#uploadFileFormPreview").html($l("uploadErrors.tooLargePersonal",{fileSize:window.serverSettings.fileUploads.sizeLimits[d]})):($("#uploadFileFormPreview").html("Loading Preview..."),a.readAsDataURL(this.files[0]),a.onloadend=function(){$("#uploadFileFormPreview").html(fim_messagePreview(window.serverSettings.fileUploads.fileContainers[d],
this.result))},console.log("file good"),$("#uploadFileForm [type=submit]").removeAttr("disabled"))}})):$("#insertDocUpload").html("Disabled.");return!1};
popup.prototype.room.prototype.newMessage=function(a){var b=this,c=fim_getUsernameDeferred(a.userId),d=fim_buildMessageLine(a.text,a.flag,a.id,a.userId,a.roomId,a.time,c);c=$('<span class="userNameDate">').append(fim_buildUsernameTag($("<span>"),a.userId,c,a.anonId,window.settings.showAvatars,!window.settings.showAvatars));if(window.settings.hideTimes)d.popover({content:function(){return fim_dateFormat($(this).attr("data-time"))},html:!1,trigger:"hover",placement:"bottom"});else{var e=$('<span class="date">').text((window.settings.showAvatars?
"":" @ ")+fim_dateFormat(a.time));window.settings.showAvatars&&e.addClass("text-muted");window.settings.showAvatars?d.append(e):c.append(e)}var f=$("<span>").attr({id:"message"+a.id,"class":"messageLine"});window.settings.showAvatars&&f.addClass("messageLineAvatar");window.settings.showAvatars&&window.settings.alternateSelfPosts&&a.userId==window.activeLogin.userData.id?f.addClass("messageLineReverse").append(d).append(c):f.append(c).append(d);if(0<$("#message"+a.id).length)console.log("existing"),
$("#message"+a.id).replaceWith(f);else{var g=!1;$("#messageList .messageLine").each(function(){if(window.settings.reversePostOrder){if($(".messageText",this).attr("data-messageId")<a.id)return $(f).insertBefore(this),g=!0,!1}else if($(".messageText",this).attr("data-messageId")>a.id)return $(f).insertBefore(this),g=!0,!1});g||$("#messageList").append(f);this.messageIndex.push(a.id);100<=this.messageIndex.length&&($("#message"+this.messageIndex[0]).remove(),this.messageIndex=this.messageIndex.slice(1,
99))}$("#message"+a.id+" img").on("load",function(){b.scrollBack()});this.scrollBack();if(this.windowBlurred){window.settings.audioDing&&window.snd.play();this.faviconFlashStart();if("object"===typeof window.external&&"undefined"!==typeof window.external.msIsSiteMode&&"undefined"!==typeof window.external.msSiteModeActivate)try{window.external.msIsSiteMode()&&window.external.msSiteModeActivate()}catch(h){}window.notify.webkitNotifySupported()&&window.settings.webkitNotifications&&$.when(fim_getUsernameDeferred(a.userId)).then(function(b){window.notify.webkitNotify("images/favicon.ico",
$("#roomName").text()+"["+b[a.userId].name+"]",a.text)})}};popup.prototype.room.prototype.scrollBack=function(){window.settings.reversePostOrder?$("#messageListContainer").scrollTop(0):$("#messageListContainer").scrollTop($("#messageListContainer")[0].scrollHeight)};popup.prototype.room.prototype.faviconFlashOnce=function(){"images/favicon.ico"===$("#favicon").attr("href")?$("#favicon").attr("href","images/favicon2.ico"):$("#favicon").attr("href","images/favicon.ico")};
popup.prototype.room.prototype.faviconFlashStart=function(){this.faviconFlashTimer||(this.faviconFlashTimer=window.setInterval(this.faviconFlashOnce,1E3))};popup.prototype.room.prototype.faviconFlashStop=function(){this.faviconFlashTimer&&(window.clearInterval(this.faviconFlashTimer),this.faviconFlashTimer=!1);$("#favicon").attr("href","images/favicon.ico")};
popup.prototype.room.prototype.onBlur=function(){this.windowBlurred=!0;this.isTyping&&(fimApi.stoppedTyping(this.options.roomId),this.isTyping=!1)};popup.prototype.room.prototype.onFocus=function(){this.windowBlurred=!1;this.faviconFlashStop()};popup.prototype.room.prototype.onVisibilityChange=function(){if("hidden"==document.visibilityState)this.onBlur();else this.onFocus()};
popup.prototype.room.prototype.onWindowResize=function(){$(window).width();var a=$(window).height();$("#messageListContainer").css("height",Math.floor(a-$("#messageListCardHeader").height()-$("#textentryBoxMessage").height()-$("#navbar").height()-65));$("#activeUsers").css("height",Math.floor(a-$("#activeUsersCardHeader").height()-$("#navbar").height()-65))};popup.prototype.room.prototype.isNeutralKeyCode=function(a){return 9==a||16<=a&&18>=a||27==a||33<=a&&40>=a||44==a||45==a||91<=a&&93>=a};
popup.prototype.room.prototype.init=function(a){var b=this,c;for(c in a)this.options[c]=a[c];document.addEventListener("visibilitychange",this.visibilitychangeListener=this.onVisibilityChange.bind(this));window.addEventListener("blur",this.blurListener=this.onBlur.bind(this));window.addEventListener("focus",this.focusListener=this.onFocus.bind(this));this.onFocus();$(window).on("resize",null,this.onWindowResize);$("#navbarSupportedContent").on("shown.bs.collapse",function(){b.onWindowResize()}).on("hidden.bs.collapse",
function(){b.onWindowResize()});$("#chatContainer").fileupload({dropZone:$("body"),pasteZone:$("textarea#messageInput"),paramName:"file",submit:function(a,c){console.log("send",c);c.url=window.serverSettings.installUrl+"api/file.php?"+$.param({_action:"create",access_token:window.sessionHash});"formData"in c||(c.formData={});c.formData.roomId=b.options.roomId;"fileName"in c.formData||(c.formData.fileName=c.originalFiles[0].name);return!0}});$("#messageList").off("keydown",".messageLine .userName, .messageLine .messageText").on("keydown",
".messageLine .userName, .messageLine .messageText",{},function(a){if("contextMenu"===window.restrictFocus)return!0;if(38===a.which)return $(this).closest(".messageLine").prev(".messageLine").find($(this).hasClass("userName")?".userName":".messageText").focus(),!1;if(37===a.which||39===a.which)return $(this).closest(".messageLine").find($(this).hasClass("userName")?".messageText":".userName").focus(),!1;if(40===a.which)return console.log("down",$(this).closest(".messageLine"),$(this).closest(".messageLine").next(".messageLine"),
$(this).hasClass("userName")),$(this).closest(".messageLine").next(".messageLine").find($(this).hasClass("userName")?".userName":".messageText").focus(),!1});$(document).bind("drop dragover",function(a){a.preventDefault()});$("#sendForm").on("submit",function(){var a=$("textarea#messageInput").val();0===a.length?dia.error("Please enter your message."):(b.sendMessage(a),$("textarea#messageInput").val(""));return!1});window.standard.notifications["room"+this.options.roomId]&&window.standard.notifications["room"+
this.options.roomId].close();fimApi.getRooms({id:this.options.roomId},{each:function(a){b.roomData=a;a.permissions.view?a.permissions.post?b.enableSender():(dia.info("You are not allowed to post in this room. You will be able to view it, though.","danger"),b.disableSender()):(window.roomId=null,window.location.hash="#rooms",dia.error("You have been restricted access from this room. Please select a new room."));a.permissions.view&&(window.roomId=a.id,fimApi.getActiveUsers({roomIds:[b.options.roomId]},
{refresh:15E3,timerId:1,begin:function(){$("ul#activeUsers").html("")},each:function(a){jQuery.each(a.rooms,function(c,d){b.userStatusChangeHandler({status:d.status,typing:d.typing,userId:a.id})})}}),fimApi.ping(b.options.roomId),b.pingInterval=window.setInterval(function(){fimApi.editUserStatus(b.options.roomId,{status:"",typing:b.typing})},6E4),$("textarea#messageInput").on("keyup",function(a){if(!b.isNeutralKeyCode(a.keyCode))return b.debounce.invoke(function(){b.isTyping&&(b.isTyping=!1,fimApi.stoppedTyping(b.options.roomId))},
2E3)}).on("keydown",function(a){13!=a.keyCode||a.shiftKey?8==a.keyCode||46==a.keyCode?b.isTyping&&(b.isTyping=!1,fimApi.stoppedTyping(b.options.roomId)):b.isNeutralKeyCode(a.keyCode)||b.isTyping||(b.isTyping=!0,fimApi.startedTyping(b.options.roomId)):($("#sendForm").submit(),a.preventDefault(),b.isTyping&&(b.isTyping=!1,fimApi.stoppedTyping(b.options.roomId)))}),$(window).on("beforeunload",null,function(){b.beforeUnload(b.options.roomId)}),fim_renderHandlebarsInPlace($("#messageListCardHeaderTemplate"),
{roomData:a}),$("#messageList").html(""),window.requestSettings[b.options.roomId]={lastMessage:null,firstRequest:!0},fimApi.getMessages({roomId:b.options.roomId},{each:function(a){b.newMessage(a)},end:function(){window.requestSettings.serverSentEvents?b.eventListener():b.getMessagesFromFallback()}}));b.onWindowResize()},exception:function(a){"idNoExist"===a.string||"roomIdInvalid"===a.string?(window.roomId=null,window.location.hash="#rooms",dia.error("That room doesn't exist. Please select a room.")):
fimApi.getDefaultExceptionHandler()(a)}})};
popup.prototype.room.prototype.close=function(){fimApi.getActiveUsers({},{timerId:1,close:!0});document.removeEventListener("visibilitychange",this.visibilitychangeListener);window.removeEventListener("blur",this.blurListener);window.removeEventListener("focus",this.focusListener);this.roomSource&&(this.roomSource.close(),this.roomSource=!1);this.eventTimeout&&window.clearTimeout(this.eventTimeout);this.pingInterval&&window.clearInterval(this.pingInterval);$("#fileupload").fileupload("destroy");$("textarea#messageInput").off("keyup").off("keydown");
$("#sendForm").off("submit");$(window).off("beforeunload");this.beforeUnload(this.options.roomId);$(window).off("resize",null,this.onWindowResize)};popup.prototype.room.prototype.setRoom=function(a){this.options.roomId&&this.options.roomId!=a&&(this.close(),this.options.lastEvent=0,this.options.lastMessage=0,this.options.roomId=a,this.init())};popup.prototype.room.prototype.beforeUnload=function(a){fimApi.exitRoom(a)};
popup.prototype.room.prototype.eventListener=function(){var a=this;this.roomSource=new EventSource(directory+"stream.php?queryId="+this.options.roomId+"&streamType=room&lastEvent="+this.options.lastEvent+"&lastMessage="+this.options.lastMessage+"&access_token="+window.sessionHash);this.roomSource.onerror=function(b){2===a.roomSource.readyState&&(a.roomSource=!1,a.getMessagesFromFallback())};var b=function(b){return function(c){a.options.lastEvent=Math.max(Number(a.options.lastEvent),Number(c.lastEventId));
b.call(a,JSON.parse(c.data))}};this.roomSource.addEventListener("userStatusChange",b(this.userStatusChangeHandler),!1);this.roomSource.addEventListener("newMessage",b(this.newMessageHandler),!1);this.roomSource.addEventListener("topicChange",b(this.topicChangeHandler),!1);this.roomSource.addEventListener("deletedMessage",b(this.deletedMessageHandler),!1);this.roomSource.addEventListener("editedMessage",b(this.editedMessageHandler),!1)};
popup.prototype.room.prototype.newMessageHandler=function(a){this.options.lastMessage=Math.max(this.options.lastMessage,a.id);this.newMessage(a)};popup.prototype.room.prototype.deletedMessageHandler=function(a){$("#message"+a.id).fadeOut()};popup.prototype.room.prototype.topicChangeHandler=function(a){$("#topic").text(a.topic);console.log("Event (Topic Change): "+a.topic)};
popup.prototype.room.prototype.editedMessageHandler=function(a){0<$("#message"+a.id).length&&(a.userId=a.senderId,a.time=$("#message"+a.id+" .messageText").attr("data-time"),this.newMessage(a))};
popup.prototype.room.prototype.userStatusChangeHandler=function(a){var b=$("ul#activeUsers > li[data-userId="+a.userId+"]"),c=$("<li>").attr("class","list-group-item").attr("data-userId",a.userId).append(fim_buildUsernameTag($("<span>"),a.userId)).append(a.typing?$('<i class="fa fa-keyboard-o" style="vertical-align: middle; margin-left: 10px;"></i>'):$(""));0<b.length?"offline"!==a.status?b.replaceWith(c):b.remove():"offline"!==a.status&&$("ul#activeUsers").append(c)};
popup.prototype.room.prototype.getMessagesFromFallback=function(){var a=this;this.options.roomId?fimApi.getEventsFallback({streamType:"room",queryId:this.options.roomId,lastEvent:this.options.lastEvent},{each:function(b){a.options.lastEvent=Math.max(Number(a.options.lastEvent),Number(b.id));a[b.eventName+"Handler"](b.data)},end:function(){window.requestSettings.serverSentEvents?a.eventListener():a.eventTimeout=window.setTimeout(function(){a.getMessagesFromFallback()},2E3)}}):console.log("Not requesting messages; room undefined.");
return!1};
popup.prototype.room.prototype.sendMessage=function(a,b,c){var d=this;this.options.roomId?fimApi.sendMessage(this.options.roomId,{ignoreBlock:1===b?1:"",message:a,flag:c?c:""},{end:function(a){"censor"in a&&0<Object.keys(a.censor).length&&dia.info(Object.values(a.censor).join("<br /><br />"),"Censor warning: "+Object.keys(a.censor).join(", "))},exception:function(b){"confirmCensor"===b.string?dia.confirm({text:b.details,"true":function(){this.sendMessage(a,1,c)}},"Censor Warning"):"spaceMessage"===b.string?
dia.error("Too... many... spaces!"):fimApi.getDefaultExceptionHandler()(b)},error:function(b){window.settings.reversePostOrder?$("#messageList").append($("<div>").text('Your message, "'+a+'", could not be sent and will be retried.')):$("#messageList").prepend($("<div>").text('Your message, "'+a+'", could not be sent and will be retried.'));window.setTimeout(function(){d.sendMessage(a)},5E3);return!1}}):window.location.hash="#rooms"};
popup.prototype.room.prototype.disableSender=function(){$("#messageInput").attr("disabled","disabled");$("#icon_url").button({disabled:!0});$("#icon_submit").button({disabled:!0});$("#icon_reset").button({disabled:!0})};popup.prototype.room.prototype.enableSender=function(){$("#messageInput").removeAttr("disabled");$("#icon_url").button({disabled:!1});$("#icon_submit").button({disabled:!1});$("#icon_reset").button({disabled:!1})};
